package com.unknown.platform.windows;

import java.util.HashMap;
import java.util.Map;

@SuppressWarnings("serial")
public class WinError extends Exception {
	public static final int ERROR_INVALID_FUNCTION = 1;
	public static final int ERROR_FILE_NOT_FOUND = 2;
	public static final int ERROR_PATH_NOT_FOUND = 3;
	public static final int ERROR_TOO_MANY_OPEN_FILES = 4;
	public static final int ERROR_ACCESS_DENIED = 5;
	public static final int ERROR_INVALID_HANDLE = 6;
	public static final int ERROR_ARENA_TRASHED = 7;
	public static final int ERROR_NOT_ENOUGH_MEMORY = 8;
	public static final int ERROR_INVALID_BLOCK = 9;
	public static final int ERROR_BAD_ENVIRONMENT = 10;
	public static final int ERROR_BAD_FORMAT = 11;
	public static final int ERROR_INVALID_ACCESS = 12;
	public static final int ERROR_INVALID_DATA = 13;
	public static final int ERROR_OUTOFMEMORY = 14;
	public static final int ERROR_INVALID_DRIVE = 15;
	public static final int ERROR_CURRENT_DIRECTORY = 16;
	public static final int ERROR_NOT_SAME_DEVICE = 17;
	public static final int ERROR_NO_MORE_FILES = 18;
	public static final int ERROR_WRITE_PROTECT = 19;
	public static final int ERROR_BAD_UNIT = 20;
	public static final int ERROR_NOT_READY = 21;
	public static final int ERROR_BAD_COMMAND = 22;
	public static final int ERROR_CRC = 23;
	public static final int ERROR_BAD_LENGTH = 24;
	public static final int ERROR_SEEK = 25;
	public static final int ERROR_NOT_DOS_DISK = 26;
	public static final int ERROR_SECTOR_NOT_FOUND = 27;
	public static final int ERROR_OUT_OF_PAPER = 28;
	public static final int ERROR_WRITE_FAULT = 29;
	public static final int ERROR_READ_FAULT = 30;
	public static final int ERROR_GEN_FAILURE = 31;
	public static final int ERROR_SHARING_VIOLATION = 32;
	public static final int ERROR_LOCK_VIOLATION = 33;
	public static final int ERROR_WRONG_DISK = 34;
	public static final int ERROR_SHARING_BUFFER_EXCEEDED = 36;
	public static final int ERROR_HANDLE_EOF = 38;
	public static final int ERROR_HANDLE_DISK_FULL = 39;
	public static final int ERROR_NOT_SUPPORTED = 50;
	public static final int ERROR_REM_NOT_LIST = 51;
	public static final int ERROR_DUP_NAME = 52;
	public static final int ERROR_BAD_NETPATH = 53;
	public static final int ERROR_NETWORK_BUSY = 54;
	public static final int ERROR_DEV_NOT_EXIST = 55;
	public static final int ERROR_TOO_MANY_CMDS = 56;
	public static final int ERROR_ADAP_HDW_ERR = 57;
	public static final int ERROR_BAD_NET_RESP = 58;
	public static final int ERROR_UNEXP_NET_ERR = 59;
	public static final int ERROR_BAD_REM_ADAP = 60;
	public static final int ERROR_PRINTQ_FULL = 61;
	public static final int ERROR_NO_SPOOL_SPACE = 62;
	public static final int ERROR_PRINT_CANCELLED = 63;
	public static final int ERROR_NETNAME_DELETED = 64;
	public static final int ERROR_NETWORK_ACCESS_DENIED = 65;
	public static final int ERROR_BAD_DEV_TYPE = 66;
	public static final int ERROR_BAD_NET_NAME = 67;
	public static final int ERROR_TOO_MANY_NAMES = 68;
	public static final int ERROR_TOO_MANY_SESS = 69;
	public static final int ERROR_SHARING_PAUSED = 70;
	public static final int ERROR_REQ_NOT_ACCEP = 71;
	public static final int ERROR_REDIR_PAUSED = 72;
	public static final int ERROR_FILE_EXISTS = 80;
	public static final int ERROR_CANNOT_MAKE = 82;
	public static final int ERROR_FAIL_I24 = 83;
	public static final int ERROR_OUT_OF_STRUCTURES = 84;
	public static final int ERROR_ALREADY_ASSIGNED = 85;
	public static final int ERROR_INVALID_PASSWORD = 86;
	public static final int ERROR_INVALID_PARAMETER = 87;
	public static final int ERROR_NET_WRITE_FAULT = 88;
	public static final int ERROR_NO_PROC_SLOTS = 89;
	public static final int ERROR_TOO_MANY_SEMAPHORES = 100;
	public static final int ERROR_EXCL_SEM_ALREADY_OWNED = 101;
	public static final int ERROR_SEM_IS_SET = 102;
	public static final int ERROR_TOO_MANY_SEM_REQUESTS = 103;
	public static final int ERROR_INVALID_AT_INTERRUPT_TIME = 104;
	public static final int ERROR_SEM_OWNER_DIED = 105;
	public static final int ERROR_SEM_USER_LIMIT = 106;
	public static final int ERROR_DISK_CHANGE = 107;
	public static final int ERROR_DRIVE_LOCKED = 108;
	public static final int ERROR_BROKEN_PIPE = 109;
	public static final int ERROR_OPEN_FAILED = 110;
	public static final int ERROR_BUFFER_OVERFLOW = 111;
	public static final int ERROR_DISK_FULL = 112;
	public static final int ERROR_NO_MORE_SEARCH_HANDLES = 113;
	public static final int ERROR_INVALID_TARGET_HANDLE = 114;
	public static final int ERROR_INVALID_CATEGORY = 117;
	public static final int ERROR_INVALID_VERIFY_SWITCH = 118;
	public static final int ERROR_BAD_DRIVER_LEVEL = 119;
	public static final int ERROR_CALL_NOT_IMPLEMENTED = 120;
	public static final int ERROR_SEM_TIMEOUT = 121;
	public static final int ERROR_INSUFFICIENT_BUFFER = 122;
	public static final int ERROR_INVALID_NAME = 123;
	public static final int ERROR_INVALID_LEVEL = 124;
	public static final int ERROR_NO_VOLUME_LABEL = 125;
	public static final int ERROR_MOD_NOT_FOUND = 126;
	public static final int ERROR_PROC_NOT_FOUND = 127;
	public static final int ERROR_WAIT_NO_CHILDREN = 128;
	public static final int ERROR_CHILD_NOT_COMPLETE = 129;
	public static final int ERROR_DIRECT_ACCESS_HANDLE = 130;
	public static final int ERROR_NEGATIVE_SEEK = 131;
	public static final int ERROR_SEEK_ON_DEVICE = 132;
	public static final int ERROR_IS_JOIN_TARGET = 133;
	public static final int ERROR_IS_JOINED = 134;
	public static final int ERROR_IS_SUBSTED = 135;
	public static final int ERROR_NOT_JOINED = 136;
	public static final int ERROR_NOT_SUBSTED = 137;
	public static final int ERROR_JOIN_TO_JOIN = 138;
	public static final int ERROR_SUBST_TO_SUBST = 139;
	public static final int ERROR_JOIN_TO_SUBST = 140;
	public static final int ERROR_SUBST_TO_JOIN = 141;
	public static final int ERROR_BUSY_DRIVE = 142;
	public static final int ERROR_SAME_DRIVE = 143;
	public static final int ERROR_DIR_NOT_ROOT = 144;
	public static final int ERROR_DIR_NOT_EMPTY = 145;
	public static final int ERROR_IS_SUBST_PATH = 146;
	public static final int ERROR_IS_JOIN_PATH = 147;
	public static final int ERROR_PATH_BUSY = 148;
	public static final int ERROR_IS_SUBST_TARGET = 149;
	public static final int ERROR_SYSTEM_TRACE = 150;
	public static final int ERROR_INVALID_EVENT_COUNT = 151;
	public static final int ERROR_TOO_MANY_MUXWAITERS = 152;
	public static final int ERROR_INVALID_LIST_FORMAT = 153;
	public static final int ERROR_LABEL_TOO_LONG = 154;
	public static final int ERROR_TOO_MANY_TCBS = 155;
	public static final int ERROR_SIGNAL_REFUSED = 156;
	public static final int ERROR_DISCARDED = 157;
	public static final int ERROR_NOT_LOCKED = 158;
	public static final int ERROR_BAD_THREADID_ADDR = 159;
	public static final int ERROR_BAD_ARGUMENTS = 160;
	public static final int ERROR_BAD_PATHNAME = 161;
	public static final int ERROR_SIGNAL_PENDING = 162;
	public static final int ERROR_MAX_THRDS_REACHED = 164;
	public static final int ERROR_LOCK_FAILED = 167;
	public static final int ERROR_BUSY = 170;
	public static final int ERROR_CANCEL_VIOLATION = 173;
	public static final int ERROR_ATOMIC_LOCKS_NOT_SUPPORTED = 174;
	public static final int ERROR_INVALID_SEGMENT_NUMBER = 180;
	public static final int ERROR_INVALID_ORDINAL = 182;
	public static final int ERROR_ALREADY_EXISTS = 183;
	public static final int ERROR_INVALID_FLAG_NUMBER = 186;
	public static final int ERROR_SEM_NOT_FOUND = 187;
	public static final int ERROR_INVALID_STARTING_CODESEG = 188;
	public static final int ERROR_INVALID_STACKSEG = 189;
	public static final int ERROR_INVALID_MODULETYPE = 190;
	public static final int ERROR_INVALID_EXE_SIGNATURE = 191;
	public static final int ERROR_EXE_MARKED_INVALID = 192;
	public static final int ERROR_BAD_EXE_FORMAT = 193;
	public static final int ERROR_ITERATED_DATA_EXCEEDS_64k = 194;
	public static final int ERROR_INVALID_MINALLOCSIZE = 195;
	public static final int ERROR_DYNLINK_FROM_INVALID_RING = 196;
	public static final int ERROR_IOPL_NOT_ENABLED = 197;
	public static final int ERROR_INVALID_SEGDPL = 198;
	public static final int ERROR_AUTODATASEG_EXCEEDS_64k = 199;
	public static final int ERROR_RING2SEG_MUST_BE_MOVABLE = 200;
	public static final int ERROR_RELOC_CHAIN_XEEDS_SEGLIM = 201;
	public static final int ERROR_INFLOOP_IN_RELOC_CHAIN = 202;
	public static final int ERROR_ENVVAR_NOT_FOUND = 203;
	public static final int ERROR_NO_SIGNAL_SENT = 205;
	public static final int ERROR_FILENAME_EXCED_RANGE = 206;
	public static final int ERROR_RING2_STACK_IN_USE = 207;
	public static final int ERROR_META_EXPANSION_TOO_LONG = 208;
	public static final int ERROR_INVALID_SIGNAL_NUMBER = 209;
	public static final int ERROR_THREAD_1_INACTIVE = 210;
	public static final int ERROR_LOCKED = 212;
	public static final int ERROR_TOO_MANY_MODULES = 214;
	public static final int ERROR_NESTING_NOT_ALLOWED = 215;
	public static final int ERROR_EXE_MACHINE_TYPE_MISMATCH = 216;
	public static final int ERROR_EXE_CANNOT_MODIFY_SIGNED_BINARY = 217;
	public static final int ERROR_EXE_CANNOT_MODIFY_STRONG_SIGNED_BINARY = 218;
	public static final int ERROR_BAD_PIPE = 230;
	public static final int ERROR_PIPE_BUSY = 231;
	public static final int ERROR_NO_DATA = 232;
	public static final int ERROR_PIPE_NOT_CONNECTED = 233;
	public static final int ERROR_MORE_DATA = 234;
	public static final int ERROR_VC_DISCONNECTED = 240;
	public static final int ERROR_INVALID_EA_NAME = 254;
	public static final int ERROR_EA_LIST_INCONSISTENT = 255;
	public static final int WAIT_TIMEOUT = 258;
	public static final int ERROR_NO_MORE_ITEMS = 259;
	public static final int ERROR_CANNOT_COPY = 266;
	public static final int ERROR_DIRECTORY = 267;
	public static final int ERROR_EAS_DIDNT_FIT = 275;
	public static final int ERROR_EA_FILE_CORRUPT = 276;
	public static final int ERROR_EA_TABLE_FULL = 277;
	public static final int ERROR_INVALID_EA_HANDLE = 278;
	public static final int ERROR_EAS_NOT_SUPPORTED = 282;
	public static final int ERROR_NOT_OWNER = 288;
	public static final int ERROR_TOO_MANY_POSTS = 298;
	public static final int ERROR_PARTIAL_COPY = 299;
	public static final int ERROR_OPLOCK_NOT_GRANTED = 300;
	public static final int ERROR_INVALID_OPLOCK_PROTOCOL = 301;
	public static final int ERROR_DISK_TOO_FRAGMENTED = 302;
	public static final int ERROR_DELETE_PENDING = 303;
	public static final int ERROR_MR_MID_NOT_FOUND = 317;
	public static final int ERROR_SCOPE_NOT_FOUND = 318;
	public static final int ERROR_INVALID_ADDRESS = 487;
	public static final int ERROR_ARITHMETIC_OVERFLOW = 534;
	public static final int ERROR_PIPE_CONNECTED = 535;
	public static final int ERROR_PIPE_LISTENING = 536;
	public static final int ERROR_EA_ACCESS_DENIED = 994;
	public static final int ERROR_OPERATION_ABORTED = 995;
	public static final int ERROR_IO_INCOMPLETE = 996;
	public static final int ERROR_IO_PENDING = 997;
	public static final int ERROR_NOACCESS = 998;
	public static final int ERROR_SWAPERROR = 999;
	public static final int ERROR_STACK_OVERFLOW = 1001;
	public static final int ERROR_INVALID_MESSAGE = 1002;
	public static final int ERROR_CAN_NOT_COMPLETE = 1003;
	public static final int ERROR_INVALID_FLAGS = 1004;
	public static final int ERROR_UNRECOGNIZED_VOLUME = 1005;
	public static final int ERROR_FILE_INVALID = 1006;
	public static final int ERROR_FULLSCREEN_MODE = 1007;
	public static final int ERROR_NO_TOKEN = 1008;
	public static final int ERROR_BADDB = 1009;
	public static final int ERROR_BADKEY = 1010;
	public static final int ERROR_CANTOPEN = 1011;
	public static final int ERROR_CANTREAD = 1012;
	public static final int ERROR_CANTWRITE = 1013;
	public static final int ERROR_REGISTRY_RECOVERED = 1014;
	public static final int ERROR_REGISTRY_CORRUPT = 1015;
	public static final int ERROR_REGISTRY_IO_FAILED = 1016;
	public static final int ERROR_NOT_REGISTRY_FILE = 1017;
	public static final int ERROR_KEY_DELETED = 1018;
	public static final int ERROR_NO_LOG_SPACE = 1019;
	public static final int ERROR_KEY_HAS_CHILDREN = 1020;
	public static final int ERROR_CHILD_MUST_BE_VOLATILE = 1021;
	public static final int ERROR_NOTIFY_ENUM_DIR = 1022;
	public static final int ERROR_DEPENDENT_SERVICES_RUNNING = 1051;
	public static final int ERROR_INVALID_SERVICE_CONTROL = 1052;
	public static final int ERROR_SERVICE_REQUEST_TIMEOUT = 1053;
	public static final int ERROR_SERVICE_NO_THREAD = 1054;
	public static final int ERROR_SERVICE_DATABASE_LOCKED = 1055;
	public static final int ERROR_SERVICE_ALREADY_RUNNING = 1056;
	public static final int ERROR_INVALID_SERVICE_ACCOUNT = 1057;
	public static final int ERROR_SERVICE_DISABLED = 1058;
	public static final int ERROR_CIRCULAR_DEPENDENCY = 1059;
	public static final int ERROR_SERVICE_DOES_NOT_EXIST = 1060;
	public static final int ERROR_SERVICE_CANNOT_ACCEPT_CTRL = 1061;
	public static final int ERROR_SERVICE_NOT_ACTIVE = 1062;
	public static final int ERROR_FAILED_SERVICE_CONTROLLER_CONNECT = 1063;
	public static final int ERROR_EXCEPTION_IN_SERVICE = 1064;
	public static final int ERROR_DATABASE_DOES_NOT_EXIST = 1065;
	public static final int ERROR_SERVICE_SPECIFIC_ERROR = 1066;
	public static final int ERROR_PROCESS_ABORTED = 1067;
	public static final int ERROR_SERVICE_DEPENDENCY_FAIL = 1068;
	public static final int ERROR_SERVICE_LOGON_FAILED = 1069;
	public static final int ERROR_SERVICE_START_HANG = 1070;
	public static final int ERROR_INVALID_SERVICE_LOCK = 1071;
	public static final int ERROR_SERVICE_MARKED_FOR_DELETE = 1072;
	public static final int ERROR_SERVICE_EXISTS = 1073;
	public static final int ERROR_ALREADY_RUNNING_LKG = 1074;
	public static final int ERROR_SERVICE_DEPENDENCY_DELETED = 1075;
	public static final int ERROR_BOOT_ALREADY_ACCEPTED = 1076;
	public static final int ERROR_SERVICE_NEVER_STARTED = 1077;
	public static final int ERROR_DUPLICATE_SERVICE_NAME = 1078;
	public static final int ERROR_DIFFERENT_SERVICE_ACCOUNT = 1079;
	public static final int ERROR_CANNOT_DETECT_DRIVER_FAILURE = 1080;
	public static final int ERROR_CANNOT_DETECT_PROCESS_ABORT = 1081;
	public static final int ERROR_NO_RECOVERY_PROGRAM = 1082;
	public static final int ERROR_SERVICE_NOT_IN_EXE = 1083;
	public static final int ERROR_NOT_SAFEBOOT_SERVICE = 1084;
	public static final int ERROR_END_OF_MEDIA = 1100;
	public static final int ERROR_FILEMARK_DETECTED = 1101;
	public static final int ERROR_BEGINNING_OF_MEDIA = 1102;
	public static final int ERROR_SETMARK_DETECTED = 1103;
	public static final int ERROR_NO_DATA_DETECTED = 1104;
	public static final int ERROR_PARTITION_FAILURE = 1105;
	public static final int ERROR_INVALID_BLOCK_LENGTH = 1106;
	public static final int ERROR_DEVICE_NOT_PARTITIONED = 1107;
	public static final int ERROR_UNABLE_TO_LOCK_MEDIA = 1108;
	public static final int ERROR_UNABLE_TO_UNLOAD_MEDIA = 1109;
	public static final int ERROR_MEDIA_CHANGED = 1110;
	public static final int ERROR_BUS_RESET = 1111;
	public static final int ERROR_NO_MEDIA_IN_DRIVE = 1112;
	public static final int ERROR_NO_UNICODE_TRANSLATION = 1113;
	public static final int ERROR_DLL_INIT_FAILED = 1114;
	public static final int ERROR_SHUTDOWN_IN_PROGRESS = 1115;
	public static final int ERROR_NO_SHUTDOWN_IN_PROGRESS = 1116;
	public static final int ERROR_IO_DEVICE = 1117;
	public static final int ERROR_SERIAL_NO_DEVICE = 1118;
	public static final int ERROR_IRQ_BUSY = 1119;
	public static final int ERROR_MORE_WRITES = 1120;
	public static final int ERROR_COUNTER_TIMEOUT = 1121;
	public static final int ERROR_FLOPPY_ID_MARK_NOT_FOUND = 1122;
	public static final int ERROR_FLOPPY_WRONG_CYLINDER = 1123;
	public static final int ERROR_FLOPPY_UNKNOWN_ERROR = 1124;
	public static final int ERROR_FLOPPY_BAD_REGISTERS = 1125;
	public static final int ERROR_DISK_RECALIBRATE_FAILED = 1126;
	public static final int ERROR_DISK_OPERATION_FAILED = 1127;
	public static final int ERROR_DISK_RESET_FAILED = 1128;
	public static final int ERROR_EOM_OVERFLOW = 1129;
	public static final int ERROR_NOT_ENOUGH_SERVER_MEMORY = 1130;
	public static final int ERROR_POSSIBLE_DEADLOCK = 1131;
	public static final int ERROR_MAPPED_ALIGNMENT = 1132;
	public static final int ERROR_SET_POWER_STATE_VETOED = 1140;
	public static final int ERROR_SET_POWER_STATE_FAILED = 1141;
	public static final int ERROR_TOO_MANY_LINKS = 1142;
	public static final int ERROR_OLD_WIN_VERSION = 1150;
	public static final int ERROR_APP_WRONG_OS = 1151;
	public static final int ERROR_SINGLE_INSTANCE_APP = 1152;
	public static final int ERROR_RMODE_APP = 1153;
	public static final int ERROR_INVALID_DLL = 1154;
	public static final int ERROR_NO_ASSOCIATION = 1155;
	public static final int ERROR_DDE_FAIL = 1156;
	public static final int ERROR_DLL_NOT_FOUND = 1157;
	public static final int ERROR_NO_MORE_USER_HANDLES = 1158;
	public static final int ERROR_MESSAGE_SYNC_ONLY = 1159;
	public static final int ERROR_SOURCE_ELEMENT_EMPTY = 1160;
	public static final int ERROR_DESTINATION_ELEMENT_FULL = 1161;
	public static final int ERROR_ILLEGAL_ELEMENT_ADDRESS = 1162;
	public static final int ERROR_MAGAZINE_NOT_PRESENT = 1163;
	public static final int ERROR_DEVICE_REINITIALIZATION_NEEDED = 1164;
	public static final int ERROR_DEVICE_REQUIRES_CLEANING = 1165;
	public static final int ERROR_DEVICE_DOOR_OPEN = 1166;
	public static final int ERROR_DEVICE_NOT_CONNECTED = 1167;
	public static final int ERROR_NOT_FOUND = 1168;
	public static final int ERROR_NO_MATCH = 1169;
	public static final int ERROR_SET_NOT_FOUND = 1170;
	public static final int ERROR_POINT_NOT_FOUND = 1171;
	public static final int ERROR_NO_TRACKING_SERVICE = 1172;
	public static final int ERROR_NO_VOLUME_ID = 1173;
	public static final int ERROR_UNABLE_TO_REMOVE_REPLACED = 1175;
	public static final int ERROR_UNABLE_TO_MOVE_REPLACEMENT = 1176;
	public static final int ERROR_UNABLE_TO_MOVE_REPLACEMENT_2 = 1177;
	public static final int ERROR_JOURNAL_DELETE_IN_PROGRESS = 1178;
	public static final int ERROR_JOURNAL_NOT_ACTIVE = 1179;
	public static final int ERROR_POTENTIAL_FILE_FOUND = 1180;
	public static final int ERROR_JOURNAL_ENTRY_DELETED = 1181;
	public static final int ERROR_BAD_DEVICE = 1200;
	public static final int ERROR_CONNECTION_UNAVAIL = 1201;
	public static final int ERROR_DEVICE_ALREADY_REMEMBERED = 1202;
	public static final int ERROR_NO_NET_OR_BAD_PATH = 1203;
	public static final int ERROR_BAD_PROVIDER = 1204;
	public static final int ERROR_CANNOT_OPEN_PROFILE = 1205;
	public static final int ERROR_BAD_PROFILE = 1206;
	public static final int ERROR_NOT_CONTAINER = 1207;
	public static final int ERROR_EXTENDED_ERROR = 1208;
	public static final int ERROR_INVALID_GROUPNAME = 1209;
	public static final int ERROR_INVALID_COMPUTERNAME = 1210;
	public static final int ERROR_INVALID_EVENTNAME = 1211;
	public static final int ERROR_INVALID_DOMAINNAME = 1212;
	public static final int ERROR_INVALID_SERVICENAME = 1213;
	public static final int ERROR_INVALID_NETNAME = 1214;
	public static final int ERROR_INVALID_SHARENAME = 1215;
	public static final int ERROR_INVALID_PASSWORDNAME = 1216;
	public static final int ERROR_INVALID_MESSAGENAME = 1217;
	public static final int ERROR_INVALID_MESSAGEDEST = 1218;
	public static final int ERROR_SESSION_CREDENTIAL_CONFLICT = 1219;
	public static final int ERROR_REMOTE_SESSION_LIMIT_EXCEEDED = 1220;
	public static final int ERROR_DUP_DOMAINNAME = 1221;
	public static final int ERROR_NO_NETWORK = 1222;
	public static final int ERROR_CANCELLED = 1223;
	public static final int ERROR_USER_MAPPED_FILE = 1224;
	public static final int ERROR_CONNECTION_REFUSED = 1225;
	public static final int ERROR_GRACEFUL_DISCONNECT = 1226;
	public static final int ERROR_ADDRESS_ALREADY_ASSOCIATED = 1227;
	public static final int ERROR_ADDRESS_NOT_ASSOCIATED = 1228;
	public static final int ERROR_CONNECTION_INVALID = 1229;
	public static final int ERROR_CONNECTION_ACTIVE = 1230;
	public static final int ERROR_NETWORK_UNREACHABLE = 1231;
	public static final int ERROR_HOST_UNREACHABLE = 1232;
	public static final int ERROR_PROTOCOL_UNREACHABLE = 1233;
	public static final int ERROR_PORT_UNREACHABLE = 1234;
	public static final int ERROR_REQUEST_ABORTED = 1235;
	public static final int ERROR_CONNECTION_ABORTED = 1236;
	public static final int ERROR_RETRY = 1237;
	public static final int ERROR_CONNECTION_COUNT_LIMIT = 1238;
	public static final int ERROR_LOGIN_TIME_RESTRICTION = 1239;
	public static final int ERROR_LOGIN_WKSTA_RESTRICTION = 1240;
	public static final int ERROR_INCORRECT_ADDRESS = 1241;
	public static final int ERROR_ALREADY_REGISTERED = 1242;
	public static final int ERROR_SERVICE_NOT_FOUND = 1243;
	public static final int ERROR_NOT_AUTHENTICATED = 1244;
	public static final int ERROR_NOT_LOGGED_ON = 1245;
	public static final int ERROR_CONTINUE = 1246;
	public static final int ERROR_ALREADY_INITIALIZED = 1247;
	public static final int ERROR_NO_MORE_DEVICES = 1248;
	public static final int ERROR_NO_SUCH_SITE = 1249;
	public static final int ERROR_DOMAIN_CONTROLLER_EXISTS = 1250;
	public static final int ERROR_ONLY_IF_CONNECTED = 1251;
	public static final int ERROR_OVERRIDE_NOCHANGES = 1252;
	public static final int ERROR_BAD_USER_PROFILE = 1253;
	public static final int ERROR_NOT_SUPPORTED_ON_SBS = 1254;
	public static final int ERROR_SERVER_SHUTDOWN_IN_PROGRESS = 1255;
	public static final int ERROR_HOST_DOWN = 1256;
	public static final int ERROR_NON_ACCOUNT_SID = 1257;
	public static final int ERROR_NON_DOMAIN_SID = 1258;
	public static final int ERROR_APPHELP_BLOCK = 1259;
	public static final int ERROR_ACCESS_DISABLED_BY_POLICY = 1260;
	public static final int ERROR_REG_NAT_CONSUMPTION = 1261;
	public static final int ERROR_CSCSHARE_OFFLINE = 1262;
	public static final int ERROR_PKINIT_FAILURE = 1263;
	public static final int ERROR_SMARTCARD_SUBSYSTEM_FAILURE = 1264;
	public static final int ERROR_DOWNGRADE_DETECTED = 1265;
	public static final int ERROR_MACHINE_LOCKED = 1271;
	public static final int ERROR_CALLBACK_SUPPLIED_INVALID_DATA = 1273;
	public static final int ERROR_SYNC_FOREGROUND_REFRESH_REQUIRED = 1274;
	public static final int ERROR_DRIVER_BLOCKED = 1275;
	public static final int ERROR_INVALID_IMPORT_OF_NON_DLL = 1276;
	public static final int ERROR_ACCESS_DISABLED_WEBBLADE = 1277;
	public static final int ERROR_ACCESS_DISABLED_WEBBLADE_TAMPER = 1278;
	public static final int ERROR_RECOVERY_FAILURE = 1279;
	public static final int ERROR_ALREADY_FIBER = 1280;
	public static final int ERROR_ALREADY_THREAD = 1281;
	public static final int ERROR_STACK_BUFFER_OVERRUN = 1282;
	public static final int ERROR_PARAMETER_QUOTA_EXCEEDED = 1283;
	public static final int ERROR_DEBUGGER_INACTIVE = 1284;
	public static final int ERROR_DELAY_LOAD_FAILED = 1285;
	public static final int ERROR_VDM_DISALLOWED = 1286;
	public static final int ERROR_UNIDENTIFIED_ERROR = 1287;
	public static final int ERROR_NOT_ALL_ASSIGNED = 1300;
	public static final int ERROR_SOME_NOT_MAPPED = 1301;
	public static final int ERROR_NO_QUOTAS_FOR_ACCOUNT = 1302;
	public static final int ERROR_LOCAL_USER_SESSION_KEY = 1303;
	public static final int ERROR_NULL_LM_PASSWORD = 1304;
	public static final int ERROR_UNKNOWN_REVISION = 1305;
	public static final int ERROR_REVISION_MISMATCH = 1306;
	public static final int ERROR_INVALID_OWNER = 1307;
	public static final int ERROR_INVALID_PRIMARY_GROUP = 1308;
	public static final int ERROR_NO_IMPERSONATION_TOKEN = 1309;
	public static final int ERROR_CANT_DISABLE_MANDATORY = 1310;
	public static final int ERROR_NO_LOGON_SERVERS = 1311;
	public static final int ERROR_NO_SUCH_LOGON_SESSION = 1312;
	public static final int ERROR_NO_SUCH_PRIVILEGE = 1313;
	public static final int ERROR_PRIVILEGE_NOT_HELD = 1314;
	public static final int ERROR_INVALID_ACCOUNT_NAME = 1315;
	public static final int ERROR_USER_EXISTS = 1316;
	public static final int ERROR_NO_SUCH_USER = 1317;
	public static final int ERROR_GROUP_EXISTS = 1318;
	public static final int ERROR_NO_SUCH_GROUP = 1319;
	public static final int ERROR_MEMBER_IN_GROUP = 1320;
	public static final int ERROR_MEMBER_NOT_IN_GROUP = 1321;
	public static final int ERROR_LAST_ADMIN = 1322;
	public static final int ERROR_WRONG_PASSWORD = 1323;
	public static final int ERROR_ILL_FORMED_PASSWORD = 1324;
	public static final int ERROR_PASSWORD_RESTRICTION = 1325;
	public static final int ERROR_LOGON_FAILURE = 1326;
	public static final int ERROR_ACCOUNT_RESTRICTION = 1327;
	public static final int ERROR_INVALID_LOGON_HOURS = 1328;
	public static final int ERROR_INVALID_WORKSTATION = 1329;
	public static final int ERROR_PASSWORD_EXPIRED = 1330;
	public static final int ERROR_ACCOUNT_DISABLED = 1331;
	public static final int ERROR_NONE_MAPPED = 1332;
	public static final int ERROR_TOO_MANY_LUIDS_REQUESTED = 1333;
	public static final int ERROR_LUIDS_EXHAUSTED = 1334;
	public static final int ERROR_INVALID_SUB_AUTHORITY = 1335;
	public static final int ERROR_INVALID_ACL = 1336;
	public static final int ERROR_INVALID_SID = 1337;
	public static final int ERROR_INVALID_SECURITY_DESCR = 1338;
	public static final int ERROR_BAD_INHERITANCE_ACL = 1340;
	public static final int ERROR_SERVER_DISABLED = 1341;
	public static final int ERROR_SERVER_NOT_DISABLED = 1342;
	public static final int ERROR_INVALID_ID_AUTHORITY = 1343;
	public static final int ERROR_ALLOTTED_SPACE_EXCEEDED = 1344;
	public static final int ERROR_INVALID_GROUP_ATTRIBUTES = 1345;
	public static final int ERROR_BAD_IMPERSONATION_LEVEL = 1346;
	public static final int ERROR_CANT_OPEN_ANONYMOUS = 1347;
	public static final int ERROR_BAD_VALIDATION_CLASS = 1348;
	public static final int ERROR_BAD_TOKEN_TYPE = 1349;
	public static final int ERROR_NO_SECURITY_ON_OBJECT = 1350;
	public static final int ERROR_CANT_ACCESS_DOMAIN_INFO = 1351;
	public static final int ERROR_INVALID_SERVER_STATE = 1352;
	public static final int ERROR_INVALID_DOMAIN_STATE = 1353;
	public static final int ERROR_INVALID_DOMAIN_ROLE = 1354;
	public static final int ERROR_NO_SUCH_DOMAIN = 1355;
	public static final int ERROR_DOMAIN_EXISTS = 1356;
	public static final int ERROR_DOMAIN_LIMIT_EXCEEDED = 1357;
	public static final int ERROR_INTERNAL_DB_CORRUPTION = 1358;
	public static final int ERROR_INTERNAL_ERROR = 1359;
	public static final int ERROR_GENERIC_NOT_MAPPED = 1360;
	public static final int ERROR_BAD_DESCRIPTOR_FORMAT = 1361;
	public static final int ERROR_NOT_LOGON_PROCESS = 1362;
	public static final int ERROR_LOGON_SESSION_EXISTS = 1363;
	public static final int ERROR_NO_SUCH_PACKAGE = 1364;
	public static final int ERROR_BAD_LOGON_SESSION_STATE = 1365;
	public static final int ERROR_LOGON_SESSION_COLLISION = 1366;
	public static final int ERROR_INVALID_LOGON_TYPE = 1367;
	public static final int ERROR_CANNOT_IMPERSONATE = 1368;
	public static final int ERROR_RXACT_INVALID_STATE = 1369;
	public static final int ERROR_RXACT_COMMIT_FAILURE = 1370;
	public static final int ERROR_SPECIAL_ACCOUNT = 1371;
	public static final int ERROR_SPECIAL_GROUP = 1372;
	public static final int ERROR_SPECIAL_USER = 1373;
	public static final int ERROR_MEMBERS_PRIMARY_GROUP = 1374;
	public static final int ERROR_TOKEN_ALREADY_IN_USE = 1375;
	public static final int ERROR_NO_SUCH_ALIAS = 1376;
	public static final int ERROR_MEMBER_NOT_IN_ALIAS = 1377;
	public static final int ERROR_MEMBER_IN_ALIAS = 1378;
	public static final int ERROR_ALIAS_EXISTS = 1379;
	public static final int ERROR_LOGON_NOT_GRANTED = 1380;
	public static final int ERROR_TOO_MANY_SECRETS = 1381;
	public static final int ERROR_SECRET_TOO_LONG = 1382;
	public static final int ERROR_INTERNAL_DB_ERROR = 1383;
	public static final int ERROR_TOO_MANY_CONTEXT_IDS = 1384;
	public static final int ERROR_LOGON_TYPE_NOT_GRANTED = 1385;
	public static final int ERROR_NT_CROSS_ENCRYPTION_REQUIRED = 1386;
	public static final int ERROR_NO_SUCH_MEMBER = 1387;
	public static final int ERROR_INVALID_MEMBER = 1388;
	public static final int ERROR_TOO_MANY_SIDS = 1389;
	public static final int ERROR_LM_CROSS_ENCRYPTION_REQUIRED = 1390;
	public static final int ERROR_NO_INHERITANCE = 1391;
	public static final int ERROR_FILE_CORRUPT = 1392;
	public static final int ERROR_DISK_CORRUPT = 1393;
	public static final int ERROR_NO_USER_SESSION_KEY = 1394;
	public static final int ERROR_LICENSE_QUOTA_EXCEEDED = 1395;
	public static final int ERROR_WRONG_TARGET_NAME = 1396;
	public static final int ERROR_MUTUAL_AUTH_FAILED = 1397;
	public static final int ERROR_TIME_SKEW = 1398;
	public static final int ERROR_CURRENT_DOMAIN_NOT_ALLOWED = 1399;
	public static final int ERROR_INVALID_WINDOW_HANDLE = 1400;
	public static final int ERROR_INVALID_MENU_HANDLE = 1401;
	public static final int ERROR_INVALID_CURSOR_HANDLE = 1402;
	public static final int ERROR_INVALID_ACCEL_HANDLE = 1403;
	public static final int ERROR_INVALID_HOOK_HANDLE = 1404;
	public static final int ERROR_INVALID_DWP_HANDLE = 1405;
	public static final int ERROR_TLW_WITH_WSCHILD = 1406;
	public static final int ERROR_CANNOT_FIND_WND_CLASS = 1407;
	public static final int ERROR_WINDOW_OF_OTHER_THREAD = 1408;
	public static final int ERROR_HOTKEY_ALREADY_REGISTERED = 1409;
	public static final int ERROR_CLASS_ALREADY_EXISTS = 1410;
	public static final int ERROR_CLASS_DOES_NOT_EXIST = 1411;
	public static final int ERROR_CLASS_HAS_WINDOWS = 1412;
	public static final int ERROR_INVALID_INDEX = 1413;
	public static final int ERROR_INVALID_ICON_HANDLE = 1414;
	public static final int ERROR_PRIVATE_DIALOG_INDEX = 1415;
	public static final int ERROR_LISTBOX_ID_NOT_FOUND = 1416;
	public static final int ERROR_NO_WILDCARD_CHARACTERS = 1417;
	public static final int ERROR_CLIPBOARD_NOT_OPEN = 1418;
	public static final int ERROR_HOTKEY_NOT_REGISTERED = 1419;
	public static final int ERROR_WINDOW_NOT_DIALOG = 1420;
	public static final int ERROR_CONTROL_ID_NOT_FOUND = 1421;
	public static final int ERROR_INVALID_COMBOBOX_MESSAGE = 1422;
	public static final int ERROR_WINDOW_NOT_COMBOBOX = 1423;
	public static final int ERROR_INVALID_EDIT_HEIGHT = 1424;
	public static final int ERROR_DC_NOT_FOUND = 1425;
	public static final int ERROR_INVALID_HOOK_FILTER = 1426;
	public static final int ERROR_INVALID_FILTER_PROC = 1427;
	public static final int ERROR_HOOK_NEEDS_HMOD = 1428;
	public static final int ERROR_GLOBAL_ONLY_HOOK = 1429;
	public static final int ERROR_JOURNAL_HOOK_SET = 1430;
	public static final int ERROR_HOOK_NOT_INSTALLED = 1431;
	public static final int ERROR_INVALID_LB_MESSAGE = 1432;
	public static final int ERROR_SETCOUNT_ON_BAD_LB = 1433;
	public static final int ERROR_LB_WITHOUT_TABSTOPS = 1434;
	public static final int ERROR_DESTROY_OBJECT_OF_OTHER_THREAD = 1435;
	public static final int ERROR_CHILD_WINDOW_MENU = 1436;
	public static final int ERROR_NO_SYSTEM_MENU = 1437;
	public static final int ERROR_INVALID_MSGBOX_STYLE = 1438;
	public static final int ERROR_INVALID_SPI_VALUE = 1439;
	public static final int ERROR_SCREEN_ALREADY_LOCKED = 1440;
	public static final int ERROR_HWNDS_HAVE_DIFF_PARENT = 1441;
	public static final int ERROR_NOT_CHILD_WINDOW = 1442;
	public static final int ERROR_INVALID_GW_COMMAND = 1443;
	public static final int ERROR_INVALID_THREAD_ID = 1444;
	public static final int ERROR_NON_MDICHILD_WINDOW = 1445;
	public static final int ERROR_POPUP_ALREADY_ACTIVE = 1446;
	public static final int ERROR_NO_SCROLLBARS = 1447;
	public static final int ERROR_INVALID_SCROLLBAR_RANGE = 1448;
	public static final int ERROR_INVALID_SHOWWIN_COMMAND = 1449;
	public static final int ERROR_NO_SYSTEM_RESOURCES = 1450;
	public static final int ERROR_NONPAGED_SYSTEM_RESOURCES = 1451;
	public static final int ERROR_PAGED_SYSTEM_RESOURCES = 1452;
	public static final int ERROR_WORKING_SET_QUOTA = 1453;
	public static final int ERROR_PAGEFILE_QUOTA = 1454;
	public static final int ERROR_COMMITMENT_LIMIT = 1455;
	public static final int ERROR_MENU_ITEM_NOT_FOUND = 1456;
	public static final int ERROR_INVALID_KEYBOARD_HANDLE = 1457;
	public static final int ERROR_HOOK_TYPE_NOT_ALLOWED = 1458;
	public static final int ERROR_REQUIRES_INTERACTIVE_WINDOWSTATION = 1459;
	public static final int ERROR_TIMEOUT = 1460;
	public static final int ERROR_INVALID_MONITOR_HANDLE = 1461;
	public static final int ERROR_INCORRECT_SIZE = 1462;
	public static final int ERROR_EVENTLOG_FILE_CORRUPT = 1500;
	public static final int ERROR_EVENTLOG_CANT_START = 1501;
	public static final int ERROR_LOG_FILE_FULL = 1502;
	public static final int ERROR_EVENTLOG_FILE_CHANGED = 1503;
	public static final int ERROR_INSTALL_SERVICE_FAILURE = 1601;
	public static final int ERROR_INSTALL_USEREXIT = 1602;
	public static final int ERROR_INSTALL_FAILURE = 1603;
	public static final int ERROR_INSTALL_SUSPEND = 1604;
	public static final int ERROR_UNKNOWN_PRODUCT = 1605;
	public static final int ERROR_UNKNOWN_FEATURE = 1606;
	public static final int ERROR_UNKNOWN_COMPONENT = 1607;
	public static final int ERROR_UNKNOWN_PROPERTY = 1608;
	public static final int ERROR_INVALID_HANDLE_STATE = 1609;
	public static final int ERROR_BAD_CONFIGURATION = 1610;
	public static final int ERROR_INDEX_ABSENT = 1611;
	public static final int ERROR_INSTALL_SOURCE_ABSENT = 1612;
	public static final int ERROR_INSTALL_PACKAGE_VERSION = 1613;
	public static final int ERROR_PRODUCT_UNINSTALLED = 1614;
	public static final int ERROR_BAD_QUERY_SYNTAX = 1615;
	public static final int ERROR_INVALID_FIELD = 1616;
	public static final int ERROR_DEVICE_REMOVED = 1617;
	public static final int ERROR_INSTALL_ALREADY_RUNNING = 1618;
	public static final int ERROR_INSTALL_PACKAGE_OPEN_FAILED = 1619;
	public static final int ERROR_INSTALL_PACKAGE_INVALID = 1620;
	public static final int ERROR_INSTALL_UI_FAILURE = 1621;
	public static final int ERROR_INSTALL_LOG_FAILURE = 1622;
	public static final int ERROR_INSTALL_LANGUAGE_UNSUPPORTED = 1623;
	public static final int ERROR_INSTALL_TRANSFORM_FAILURE = 1624;
	public static final int ERROR_INSTALL_PACKAGE_REJECTED = 1625;
	public static final int ERROR_FUNCTION_NOT_CALLED = 1626;
	public static final int ERROR_FUNCTION_FAILED = 1627;
	public static final int ERROR_INVALID_TABLE = 1628;
	public static final int ERROR_DATATYPE_MISMATCH = 1629;
	public static final int ERROR_UNSUPPORTED_TYPE = 1630;
	public static final int ERROR_CREATE_FAILED = 1631;
	public static final int ERROR_INSTALL_TEMP_UNWRITABLE = 1632;
	public static final int ERROR_INSTALL_PLATFORM_UNSUPPORTED = 1633;
	public static final int ERROR_INSTALL_NOTUSED = 1634;
	public static final int ERROR_PATCH_PACKAGE_OPEN_FAILED = 1635;
	public static final int ERROR_PATCH_PACKAGE_INVALID = 1636;
	public static final int ERROR_PATCH_PACKAGE_UNSUPPORTED = 1637;
	public static final int ERROR_PRODUCT_VERSION = 1638;
	public static final int ERROR_INVALID_COMMAND_LINE = 1639;
	public static final int ERROR_INSTALL_REMOTE_DISALLOWED = 1640;
	public static final int ERROR_SUCCESS_REBOOT_INITIATED = 1641;
	public static final int ERROR_PATCH_TARGET_NOT_FOUND = 1642;
	public static final int ERROR_PATCH_PACKAGE_REJECTED = 1643;
	public static final int ERROR_INSTALL_TRANSFORM_REJECTED = 1644;
	public static final int ERROR_INSTALL_REMOTE_PROHIBITED = 1645;

	private static final Map<Integer, String> ERROR_NAMES;

	private final int errorcode;

	static {
		ERROR_NAMES = new HashMap<>();

		ERROR_NAMES.put(ERROR_INVALID_FUNCTION, "ERROR_INVALID_FUNCTION");
		ERROR_NAMES.put(ERROR_FILE_NOT_FOUND, "ERROR_FILE_NOT_FOUND");
		ERROR_NAMES.put(ERROR_PATH_NOT_FOUND, "ERROR_PATH_NOT_FOUND");
		ERROR_NAMES.put(ERROR_TOO_MANY_OPEN_FILES, "ERROR_TOO_MANY_OPEN_FILES");
		ERROR_NAMES.put(ERROR_ACCESS_DENIED, "ERROR_ACCESS_DENIED");
		ERROR_NAMES.put(ERROR_INVALID_HANDLE, "ERROR_INVALID_HANDLE");
		ERROR_NAMES.put(ERROR_ARENA_TRASHED, "ERROR_ARENA_TRASHED");
		ERROR_NAMES.put(ERROR_NOT_ENOUGH_MEMORY, "ERROR_NOT_ENOUGH_MEMORY");
		ERROR_NAMES.put(ERROR_INVALID_BLOCK, "ERROR_INVALID_BLOCK");
		ERROR_NAMES.put(ERROR_BAD_ENVIRONMENT, "ERROR_BAD_ENVIRONMENT");
		ERROR_NAMES.put(ERROR_BAD_FORMAT, "ERROR_BAD_FORMAT");
		ERROR_NAMES.put(ERROR_INVALID_ACCESS, "ERROR_INVALID_ACCESS");
		ERROR_NAMES.put(ERROR_INVALID_DATA, "ERROR_INVALID_DATA");
		ERROR_NAMES.put(ERROR_OUTOFMEMORY, "ERROR_OUTOFMEMORY");
		ERROR_NAMES.put(ERROR_INVALID_DRIVE, "ERROR_INVALID_DRIVE");
		ERROR_NAMES.put(ERROR_CURRENT_DIRECTORY, "ERROR_CURRENT_DIRECTORY");
		ERROR_NAMES.put(ERROR_NOT_SAME_DEVICE, "ERROR_NOT_SAME_DEVICE");
		ERROR_NAMES.put(ERROR_NO_MORE_FILES, "ERROR_NO_MORE_FILES");
		ERROR_NAMES.put(ERROR_WRITE_PROTECT, "ERROR_WRITE_PROTECT");
		ERROR_NAMES.put(ERROR_BAD_UNIT, "ERROR_BAD_UNIT");
		ERROR_NAMES.put(ERROR_NOT_READY, "ERROR_NOT_READY");
		ERROR_NAMES.put(ERROR_BAD_COMMAND, "ERROR_BAD_COMMAND");
		ERROR_NAMES.put(ERROR_CRC, "ERROR_CRC");
		ERROR_NAMES.put(ERROR_BAD_LENGTH, "ERROR_BAD_LENGTH");
		ERROR_NAMES.put(ERROR_SEEK, "ERROR_SEEK");
		ERROR_NAMES.put(ERROR_NOT_DOS_DISK, "ERROR_NOT_DOS_DISK");
		ERROR_NAMES.put(ERROR_SECTOR_NOT_FOUND, "ERROR_SECTOR_NOT_FOUND");
		ERROR_NAMES.put(ERROR_OUT_OF_PAPER, "ERROR_OUT_OF_PAPER");
		ERROR_NAMES.put(ERROR_WRITE_FAULT, "ERROR_WRITE_FAULT");
		ERROR_NAMES.put(ERROR_READ_FAULT, "ERROR_READ_FAULT");
		ERROR_NAMES.put(ERROR_GEN_FAILURE, "ERROR_GEN_FAILURE");
		ERROR_NAMES.put(ERROR_SHARING_VIOLATION, "ERROR_SHARING_VIOLATION");
		ERROR_NAMES.put(ERROR_LOCK_VIOLATION, "ERROR_LOCK_VIOLATION");
		ERROR_NAMES.put(ERROR_WRONG_DISK, "ERROR_WRONG_DISK");
		ERROR_NAMES.put(ERROR_SHARING_BUFFER_EXCEEDED, "ERROR_SHARING_BUFFER_EXCEEDED");
		ERROR_NAMES.put(ERROR_HANDLE_EOF, "ERROR_HANDLE_EOF");
		ERROR_NAMES.put(ERROR_HANDLE_DISK_FULL, "ERROR_HANDLE_DISK_FULL");
		ERROR_NAMES.put(ERROR_NOT_SUPPORTED, "ERROR_NOT_SUPPORTED");
		ERROR_NAMES.put(ERROR_REM_NOT_LIST, "ERROR_REM_NOT_LIST");
		ERROR_NAMES.put(ERROR_DUP_NAME, "ERROR_DUP_NAME");
		ERROR_NAMES.put(ERROR_BAD_NETPATH, "ERROR_BAD_NETPATH");
		ERROR_NAMES.put(ERROR_NETWORK_BUSY, "ERROR_NETWORK_BUSY");
		ERROR_NAMES.put(ERROR_DEV_NOT_EXIST, "ERROR_DEV_NOT_EXIST");
		ERROR_NAMES.put(ERROR_TOO_MANY_CMDS, "ERROR_TOO_MANY_CMDS");
		ERROR_NAMES.put(ERROR_ADAP_HDW_ERR, "ERROR_ADAP_HDW_ERR");
		ERROR_NAMES.put(ERROR_BAD_NET_RESP, "ERROR_BAD_NET_RESP");
		ERROR_NAMES.put(ERROR_UNEXP_NET_ERR, "ERROR_UNEXP_NET_ERR");
		ERROR_NAMES.put(ERROR_BAD_REM_ADAP, "ERROR_BAD_REM_ADAP");
		ERROR_NAMES.put(ERROR_PRINTQ_FULL, "ERROR_PRINTQ_FULL");
		ERROR_NAMES.put(ERROR_NO_SPOOL_SPACE, "ERROR_NO_SPOOL_SPACE");
		ERROR_NAMES.put(ERROR_PRINT_CANCELLED, "ERROR_PRINT_CANCELLED");
		ERROR_NAMES.put(ERROR_NETNAME_DELETED, "ERROR_NETNAME_DELETED");
		ERROR_NAMES.put(ERROR_NETWORK_ACCESS_DENIED, "ERROR_NETWORK_ACCESS_DENIED");
		ERROR_NAMES.put(ERROR_BAD_DEV_TYPE, "ERROR_BAD_DEV_TYPE");
		ERROR_NAMES.put(ERROR_BAD_NET_NAME, "ERROR_BAD_NET_NAME");
		ERROR_NAMES.put(ERROR_TOO_MANY_NAMES, "ERROR_TOO_MANY_NAMES");
		ERROR_NAMES.put(ERROR_TOO_MANY_SESS, "ERROR_TOO_MANY_SESS");
		ERROR_NAMES.put(ERROR_SHARING_PAUSED, "ERROR_SHARING_PAUSED");
		ERROR_NAMES.put(ERROR_REQ_NOT_ACCEP, "ERROR_REQ_NOT_ACCEP");
		ERROR_NAMES.put(ERROR_REDIR_PAUSED, "ERROR_REDIR_PAUSED");
		ERROR_NAMES.put(ERROR_FILE_EXISTS, "ERROR_FILE_EXISTS");
		ERROR_NAMES.put(ERROR_CANNOT_MAKE, "ERROR_CANNOT_MAKE");
		ERROR_NAMES.put(ERROR_FAIL_I24, "ERROR_FAIL_I24");
		ERROR_NAMES.put(ERROR_OUT_OF_STRUCTURES, "ERROR_OUT_OF_STRUCTURES");
		ERROR_NAMES.put(ERROR_ALREADY_ASSIGNED, "ERROR_ALREADY_ASSIGNED");
		ERROR_NAMES.put(ERROR_INVALID_PASSWORD, "ERROR_INVALID_PASSWORD");
		ERROR_NAMES.put(ERROR_INVALID_PARAMETER, "ERROR_INVALID_PARAMETER");
		ERROR_NAMES.put(ERROR_NET_WRITE_FAULT, "ERROR_NET_WRITE_FAULT");
		ERROR_NAMES.put(ERROR_NO_PROC_SLOTS, "ERROR_NO_PROC_SLOTS");
		ERROR_NAMES.put(ERROR_TOO_MANY_SEMAPHORES, "ERROR_TOO_MANY_SEMAPHORES");
		ERROR_NAMES.put(ERROR_EXCL_SEM_ALREADY_OWNED, "ERROR_EXCL_SEM_ALREADY_OWNED");
		ERROR_NAMES.put(ERROR_SEM_IS_SET, "ERROR_SEM_IS_SET");
		ERROR_NAMES.put(ERROR_TOO_MANY_SEM_REQUESTS, "ERROR_TOO_MANY_SEM_REQUESTS");
		ERROR_NAMES.put(ERROR_INVALID_AT_INTERRUPT_TIME, "ERROR_INVALID_AT_INTERRUPT_TIME");
		ERROR_NAMES.put(ERROR_SEM_OWNER_DIED, "ERROR_SEM_OWNER_DIED");
		ERROR_NAMES.put(ERROR_SEM_USER_LIMIT, "ERROR_SEM_USER_LIMIT");
		ERROR_NAMES.put(ERROR_DISK_CHANGE, "ERROR_DISK_CHANGE");
		ERROR_NAMES.put(ERROR_DRIVE_LOCKED, "ERROR_DRIVE_LOCKED");
		ERROR_NAMES.put(ERROR_BROKEN_PIPE, "ERROR_BROKEN_PIPE");
		ERROR_NAMES.put(ERROR_OPEN_FAILED, "ERROR_OPEN_FAILED");
		ERROR_NAMES.put(ERROR_BUFFER_OVERFLOW, "ERROR_BUFFER_OVERFLOW");
		ERROR_NAMES.put(ERROR_DISK_FULL, "ERROR_DISK_FULL");
		ERROR_NAMES.put(ERROR_NO_MORE_SEARCH_HANDLES, "ERROR_NO_MORE_SEARCH_HANDLES");
		ERROR_NAMES.put(ERROR_INVALID_TARGET_HANDLE, "ERROR_INVALID_TARGET_HANDLE");
		ERROR_NAMES.put(ERROR_INVALID_CATEGORY, "ERROR_INVALID_CATEGORY");
		ERROR_NAMES.put(ERROR_INVALID_VERIFY_SWITCH, "ERROR_INVALID_VERIFY_SWITCH");
		ERROR_NAMES.put(ERROR_BAD_DRIVER_LEVEL, "ERROR_BAD_DRIVER_LEVEL");
		ERROR_NAMES.put(ERROR_CALL_NOT_IMPLEMENTED, "ERROR_CALL_NOT_IMPLEMENTED");
		ERROR_NAMES.put(ERROR_SEM_TIMEOUT, "ERROR_SEM_TIMEOUT");
		ERROR_NAMES.put(ERROR_INSUFFICIENT_BUFFER, "ERROR_INSUFFICIENT_BUFFER");
		ERROR_NAMES.put(ERROR_INVALID_NAME, "ERROR_INVALID_NAME");
		ERROR_NAMES.put(ERROR_INVALID_LEVEL, "ERROR_INVALID_LEVEL");
		ERROR_NAMES.put(ERROR_NO_VOLUME_LABEL, "ERROR_NO_VOLUME_LABEL");
		ERROR_NAMES.put(ERROR_MOD_NOT_FOUND, "ERROR_MOD_NOT_FOUND");
		ERROR_NAMES.put(ERROR_PROC_NOT_FOUND, "ERROR_PROC_NOT_FOUND");
		ERROR_NAMES.put(ERROR_WAIT_NO_CHILDREN, "ERROR_WAIT_NO_CHILDREN");
		ERROR_NAMES.put(ERROR_CHILD_NOT_COMPLETE, "ERROR_CHILD_NOT_COMPLETE");
		ERROR_NAMES.put(ERROR_DIRECT_ACCESS_HANDLE, "ERROR_DIRECT_ACCESS_HANDLE");
		ERROR_NAMES.put(ERROR_NEGATIVE_SEEK, "ERROR_NEGATIVE_SEEK");
		ERROR_NAMES.put(ERROR_SEEK_ON_DEVICE, "ERROR_SEEK_ON_DEVICE");
		ERROR_NAMES.put(ERROR_IS_JOIN_TARGET, "ERROR_IS_JOIN_TARGET");
		ERROR_NAMES.put(ERROR_IS_JOINED, "ERROR_IS_JOINED");
		ERROR_NAMES.put(ERROR_IS_SUBSTED, "ERROR_IS_SUBSTED");
		ERROR_NAMES.put(ERROR_NOT_JOINED, "ERROR_NOT_JOINED");
		ERROR_NAMES.put(ERROR_NOT_SUBSTED, "ERROR_NOT_SUBSTED");
		ERROR_NAMES.put(ERROR_JOIN_TO_JOIN, "ERROR_JOIN_TO_JOIN");
		ERROR_NAMES.put(ERROR_SUBST_TO_SUBST, "ERROR_SUBST_TO_SUBST");
		ERROR_NAMES.put(ERROR_JOIN_TO_SUBST, "ERROR_JOIN_TO_SUBST");
		ERROR_NAMES.put(ERROR_SUBST_TO_JOIN, "ERROR_SUBST_TO_JOIN");
		ERROR_NAMES.put(ERROR_BUSY_DRIVE, "ERROR_BUSY_DRIVE");
		ERROR_NAMES.put(ERROR_SAME_DRIVE, "ERROR_SAME_DRIVE");
		ERROR_NAMES.put(ERROR_DIR_NOT_ROOT, "ERROR_DIR_NOT_ROOT");
		ERROR_NAMES.put(ERROR_DIR_NOT_EMPTY, "ERROR_DIR_NOT_EMPTY");
		ERROR_NAMES.put(ERROR_IS_SUBST_PATH, "ERROR_IS_SUBST_PATH");
		ERROR_NAMES.put(ERROR_IS_JOIN_PATH, "ERROR_IS_JOIN_PATH");
		ERROR_NAMES.put(ERROR_PATH_BUSY, "ERROR_PATH_BUSY");
		ERROR_NAMES.put(ERROR_IS_SUBST_TARGET, "ERROR_IS_SUBST_TARGET");
		ERROR_NAMES.put(ERROR_SYSTEM_TRACE, "ERROR_SYSTEM_TRACE");
		ERROR_NAMES.put(ERROR_INVALID_EVENT_COUNT, "ERROR_INVALID_EVENT_COUNT");
		ERROR_NAMES.put(ERROR_TOO_MANY_MUXWAITERS, "ERROR_TOO_MANY_MUXWAITERS");
		ERROR_NAMES.put(ERROR_INVALID_LIST_FORMAT, "ERROR_INVALID_LIST_FORMAT");
		ERROR_NAMES.put(ERROR_LABEL_TOO_LONG, "ERROR_LABEL_TOO_LONG");
		ERROR_NAMES.put(ERROR_TOO_MANY_TCBS, "ERROR_TOO_MANY_TCBS");
		ERROR_NAMES.put(ERROR_SIGNAL_REFUSED, "ERROR_SIGNAL_REFUSED");
		ERROR_NAMES.put(ERROR_DISCARDED, "ERROR_DISCARDED");
		ERROR_NAMES.put(ERROR_NOT_LOCKED, "ERROR_NOT_LOCKED");
		ERROR_NAMES.put(ERROR_BAD_THREADID_ADDR, "ERROR_BAD_THREADID_ADDR");
		ERROR_NAMES.put(ERROR_BAD_ARGUMENTS, "ERROR_BAD_ARGUMENTS");
		ERROR_NAMES.put(ERROR_BAD_PATHNAME, "ERROR_BAD_PATHNAME");
		ERROR_NAMES.put(ERROR_SIGNAL_PENDING, "ERROR_SIGNAL_PENDING");
		ERROR_NAMES.put(ERROR_MAX_THRDS_REACHED, "ERROR_MAX_THRDS_REACHED");
		ERROR_NAMES.put(ERROR_LOCK_FAILED, "ERROR_LOCK_FAILED");
		ERROR_NAMES.put(ERROR_BUSY, "ERROR_BUSY");
		ERROR_NAMES.put(ERROR_CANCEL_VIOLATION, "ERROR_CANCEL_VIOLATION");
		ERROR_NAMES.put(ERROR_ATOMIC_LOCKS_NOT_SUPPORTED, "ERROR_ATOMIC_LOCKS_NOT_SUPPORTED");
		ERROR_NAMES.put(ERROR_INVALID_SEGMENT_NUMBER, "ERROR_INVALID_SEGMENT_NUMBER");
		ERROR_NAMES.put(ERROR_INVALID_ORDINAL, "ERROR_INVALID_ORDINAL");
		ERROR_NAMES.put(ERROR_ALREADY_EXISTS, "ERROR_ALREADY_EXISTS");
		ERROR_NAMES.put(ERROR_INVALID_FLAG_NUMBER, "ERROR_INVALID_FLAG_NUMBER");
		ERROR_NAMES.put(ERROR_SEM_NOT_FOUND, "ERROR_SEM_NOT_FOUND");
		ERROR_NAMES.put(ERROR_INVALID_STARTING_CODESEG, "ERROR_INVALID_STARTING_CODESEG");
		ERROR_NAMES.put(ERROR_INVALID_STACKSEG, "ERROR_INVALID_STACKSEG");
		ERROR_NAMES.put(ERROR_INVALID_MODULETYPE, "ERROR_INVALID_MODULETYPE");
		ERROR_NAMES.put(ERROR_INVALID_EXE_SIGNATURE, "ERROR_INVALID_EXE_SIGNATURE");
		ERROR_NAMES.put(ERROR_EXE_MARKED_INVALID, "ERROR_EXE_MARKED_INVALID");
		ERROR_NAMES.put(ERROR_BAD_EXE_FORMAT, "ERROR_BAD_EXE_FORMAT");
		ERROR_NAMES.put(ERROR_ITERATED_DATA_EXCEEDS_64k, "ERROR_ITERATED_DATA_EXCEEDS_64k");
		ERROR_NAMES.put(ERROR_INVALID_MINALLOCSIZE, "ERROR_INVALID_MINALLOCSIZE");
		ERROR_NAMES.put(ERROR_DYNLINK_FROM_INVALID_RING, "ERROR_DYNLINK_FROM_INVALID_RING");
		ERROR_NAMES.put(ERROR_IOPL_NOT_ENABLED, "ERROR_IOPL_NOT_ENABLED");
		ERROR_NAMES.put(ERROR_INVALID_SEGDPL, "ERROR_INVALID_SEGDPL");
		ERROR_NAMES.put(ERROR_AUTODATASEG_EXCEEDS_64k, "ERROR_AUTODATASEG_EXCEEDS_64k");
		ERROR_NAMES.put(ERROR_RING2SEG_MUST_BE_MOVABLE, "ERROR_RING2SEG_MUST_BE_MOVABLE");
		ERROR_NAMES.put(ERROR_RELOC_CHAIN_XEEDS_SEGLIM, "ERROR_RELOC_CHAIN_XEEDS_SEGLIM");
		ERROR_NAMES.put(ERROR_INFLOOP_IN_RELOC_CHAIN, "ERROR_INFLOOP_IN_RELOC_CHAIN");
		ERROR_NAMES.put(ERROR_ENVVAR_NOT_FOUND, "ERROR_ENVVAR_NOT_FOUND");
		ERROR_NAMES.put(ERROR_NO_SIGNAL_SENT, "ERROR_NO_SIGNAL_SENT");
		ERROR_NAMES.put(ERROR_FILENAME_EXCED_RANGE, "ERROR_FILENAME_EXCED_RANGE");
		ERROR_NAMES.put(ERROR_RING2_STACK_IN_USE, "ERROR_RING2_STACK_IN_USE");
		ERROR_NAMES.put(ERROR_META_EXPANSION_TOO_LONG, "ERROR_META_EXPANSION_TOO_LONG");
		ERROR_NAMES.put(ERROR_INVALID_SIGNAL_NUMBER, "ERROR_INVALID_SIGNAL_NUMBER");
		ERROR_NAMES.put(ERROR_THREAD_1_INACTIVE, "ERROR_THREAD_1_INACTIVE");
		ERROR_NAMES.put(ERROR_LOCKED, "ERROR_LOCKED");
		ERROR_NAMES.put(ERROR_TOO_MANY_MODULES, "ERROR_TOO_MANY_MODULES");
		ERROR_NAMES.put(ERROR_NESTING_NOT_ALLOWED, "ERROR_NESTING_NOT_ALLOWED");
		ERROR_NAMES.put(ERROR_EXE_MACHINE_TYPE_MISMATCH, "ERROR_EXE_MACHINE_TYPE_MISMATCH");
		ERROR_NAMES.put(ERROR_EXE_CANNOT_MODIFY_SIGNED_BINARY, "ERROR_EXE_CANNOT_MODIFY_SIGNED_BINARY");
		ERROR_NAMES.put(ERROR_EXE_CANNOT_MODIFY_STRONG_SIGNED_BINARY,
				"ERROR_EXE_CANNOT_MODIFY_STRONG_SIGNED_BINARY");
		ERROR_NAMES.put(ERROR_BAD_PIPE, "ERROR_BAD_PIPE");
		ERROR_NAMES.put(ERROR_PIPE_BUSY, "ERROR_PIPE_BUSY");
		ERROR_NAMES.put(ERROR_NO_DATA, "ERROR_NO_DATA");
		ERROR_NAMES.put(ERROR_PIPE_NOT_CONNECTED, "ERROR_PIPE_NOT_CONNECTED");
		ERROR_NAMES.put(ERROR_MORE_DATA, "ERROR_MORE_DATA");
		ERROR_NAMES.put(ERROR_VC_DISCONNECTED, "ERROR_VC_DISCONNECTED");
		ERROR_NAMES.put(ERROR_INVALID_EA_NAME, "ERROR_INVALID_EA_NAME");
		ERROR_NAMES.put(ERROR_EA_LIST_INCONSISTENT, "ERROR_EA_LIST_INCONSISTENT");
		ERROR_NAMES.put(WAIT_TIMEOUT, "WAIT_TIMEOUT");
		ERROR_NAMES.put(ERROR_NO_MORE_ITEMS, "ERROR_NO_MORE_ITEMS");
		ERROR_NAMES.put(ERROR_CANNOT_COPY, "ERROR_CANNOT_COPY");
		ERROR_NAMES.put(ERROR_DIRECTORY, "ERROR_DIRECTORY");
		ERROR_NAMES.put(ERROR_EAS_DIDNT_FIT, "ERROR_EAS_DIDNT_FIT");
		ERROR_NAMES.put(ERROR_EA_FILE_CORRUPT, "ERROR_EA_FILE_CORRUPT");
		ERROR_NAMES.put(ERROR_EA_TABLE_FULL, "ERROR_EA_TABLE_FULL");
		ERROR_NAMES.put(ERROR_INVALID_EA_HANDLE, "ERROR_INVALID_EA_HANDLE");
		ERROR_NAMES.put(ERROR_EAS_NOT_SUPPORTED, "ERROR_EAS_NOT_SUPPORTED");
		ERROR_NAMES.put(ERROR_NOT_OWNER, "ERROR_NOT_OWNER");
		ERROR_NAMES.put(ERROR_TOO_MANY_POSTS, "ERROR_TOO_MANY_POSTS");
		ERROR_NAMES.put(ERROR_PARTIAL_COPY, "ERROR_PARTIAL_COPY");
		ERROR_NAMES.put(ERROR_OPLOCK_NOT_GRANTED, "ERROR_OPLOCK_NOT_GRANTED");
		ERROR_NAMES.put(ERROR_INVALID_OPLOCK_PROTOCOL, "ERROR_INVALID_OPLOCK_PROTOCOL");
		ERROR_NAMES.put(ERROR_DISK_TOO_FRAGMENTED, "ERROR_DISK_TOO_FRAGMENTED");
		ERROR_NAMES.put(ERROR_DELETE_PENDING, "ERROR_DELETE_PENDING");
		ERROR_NAMES.put(ERROR_MR_MID_NOT_FOUND, "ERROR_MR_MID_NOT_FOUND");
		ERROR_NAMES.put(ERROR_SCOPE_NOT_FOUND, "ERROR_SCOPE_NOT_FOUND");
		ERROR_NAMES.put(ERROR_INVALID_ADDRESS, "ERROR_INVALID_ADDRESS");
		ERROR_NAMES.put(ERROR_ARITHMETIC_OVERFLOW, "ERROR_ARITHMETIC_OVERFLOW");
		ERROR_NAMES.put(ERROR_PIPE_CONNECTED, "ERROR_PIPE_CONNECTED");
		ERROR_NAMES.put(ERROR_PIPE_LISTENING, "ERROR_PIPE_LISTENING");
		ERROR_NAMES.put(ERROR_EA_ACCESS_DENIED, "ERROR_EA_ACCESS_DENIED");
		ERROR_NAMES.put(ERROR_OPERATION_ABORTED, "ERROR_OPERATION_ABORTED");
		ERROR_NAMES.put(ERROR_IO_INCOMPLETE, "ERROR_IO_INCOMPLETE");
		ERROR_NAMES.put(ERROR_IO_PENDING, "ERROR_IO_PENDING");
		ERROR_NAMES.put(ERROR_NOACCESS, "ERROR_NOACCESS");
		ERROR_NAMES.put(ERROR_SWAPERROR, "ERROR_SWAPERROR");
		ERROR_NAMES.put(ERROR_STACK_OVERFLOW, "ERROR_STACK_OVERFLOW");
		ERROR_NAMES.put(ERROR_INVALID_MESSAGE, "ERROR_INVALID_MESSAGE");
		ERROR_NAMES.put(ERROR_CAN_NOT_COMPLETE, "ERROR_CAN_NOT_COMPLETE");
		ERROR_NAMES.put(ERROR_INVALID_FLAGS, "ERROR_INVALID_FLAGS");
		ERROR_NAMES.put(ERROR_UNRECOGNIZED_VOLUME, "ERROR_UNRECOGNIZED_VOLUME");
		ERROR_NAMES.put(ERROR_FILE_INVALID, "ERROR_FILE_INVALID");
		ERROR_NAMES.put(ERROR_FULLSCREEN_MODE, "ERROR_FULLSCREEN_MODE");
		ERROR_NAMES.put(ERROR_NO_TOKEN, "ERROR_NO_TOKEN");
		ERROR_NAMES.put(ERROR_BADDB, "ERROR_BADDB");
		ERROR_NAMES.put(ERROR_BADKEY, "ERROR_BADKEY");
		ERROR_NAMES.put(ERROR_CANTOPEN, "ERROR_CANTOPEN");
		ERROR_NAMES.put(ERROR_CANTREAD, "ERROR_CANTREAD");
		ERROR_NAMES.put(ERROR_CANTWRITE, "ERROR_CANTWRITE");
		ERROR_NAMES.put(ERROR_REGISTRY_RECOVERED, "ERROR_REGISTRY_RECOVERED");
		ERROR_NAMES.put(ERROR_REGISTRY_CORRUPT, "ERROR_REGISTRY_CORRUPT");
		ERROR_NAMES.put(ERROR_REGISTRY_IO_FAILED, "ERROR_REGISTRY_IO_FAILED");
		ERROR_NAMES.put(ERROR_NOT_REGISTRY_FILE, "ERROR_NOT_REGISTRY_FILE");
		ERROR_NAMES.put(ERROR_KEY_DELETED, "ERROR_KEY_DELETED");
		ERROR_NAMES.put(ERROR_NO_LOG_SPACE, "ERROR_NO_LOG_SPACE");
		ERROR_NAMES.put(ERROR_KEY_HAS_CHILDREN, "ERROR_KEY_HAS_CHILDREN");
		ERROR_NAMES.put(ERROR_CHILD_MUST_BE_VOLATILE, "ERROR_CHILD_MUST_BE_VOLATILE");
		ERROR_NAMES.put(ERROR_NOTIFY_ENUM_DIR, "ERROR_NOTIFY_ENUM_DIR");
		ERROR_NAMES.put(ERROR_DEPENDENT_SERVICES_RUNNING, "ERROR_DEPENDENT_SERVICES_RUNNING");
		ERROR_NAMES.put(ERROR_INVALID_SERVICE_CONTROL, "ERROR_INVALID_SERVICE_CONTROL");
		ERROR_NAMES.put(ERROR_SERVICE_REQUEST_TIMEOUT, "ERROR_SERVICE_REQUEST_TIMEOUT");
		ERROR_NAMES.put(ERROR_SERVICE_NO_THREAD, "ERROR_SERVICE_NO_THREAD");
		ERROR_NAMES.put(ERROR_SERVICE_DATABASE_LOCKED, "ERROR_SERVICE_DATABASE_LOCKED");
		ERROR_NAMES.put(ERROR_SERVICE_ALREADY_RUNNING, "ERROR_SERVICE_ALREADY_RUNNING");
		ERROR_NAMES.put(ERROR_INVALID_SERVICE_ACCOUNT, "ERROR_INVALID_SERVICE_ACCOUNT");
		ERROR_NAMES.put(ERROR_SERVICE_DISABLED, "ERROR_SERVICE_DISABLED");
		ERROR_NAMES.put(ERROR_CIRCULAR_DEPENDENCY, "ERROR_CIRCULAR_DEPENDENCY");
		ERROR_NAMES.put(ERROR_SERVICE_DOES_NOT_EXIST, "ERROR_SERVICE_DOES_NOT_EXIST");
		ERROR_NAMES.put(ERROR_SERVICE_CANNOT_ACCEPT_CTRL, "ERROR_SERVICE_CANNOT_ACCEPT_CTRL");
		ERROR_NAMES.put(ERROR_SERVICE_NOT_ACTIVE, "ERROR_SERVICE_NOT_ACTIVE");
		ERROR_NAMES.put(ERROR_FAILED_SERVICE_CONTROLLER_CONNECT, "ERROR_FAILED_SERVICE_CONTROLLER_CONNECT");
		ERROR_NAMES.put(ERROR_EXCEPTION_IN_SERVICE, "ERROR_EXCEPTION_IN_SERVICE");
		ERROR_NAMES.put(ERROR_DATABASE_DOES_NOT_EXIST, "ERROR_DATABASE_DOES_NOT_EXIST");
		ERROR_NAMES.put(ERROR_SERVICE_SPECIFIC_ERROR, "ERROR_SERVICE_SPECIFIC_ERROR");
		ERROR_NAMES.put(ERROR_PROCESS_ABORTED, "ERROR_PROCESS_ABORTED");
		ERROR_NAMES.put(ERROR_SERVICE_DEPENDENCY_FAIL, "ERROR_SERVICE_DEPENDENCY_FAIL");
		ERROR_NAMES.put(ERROR_SERVICE_LOGON_FAILED, "ERROR_SERVICE_LOGON_FAILED");
		ERROR_NAMES.put(ERROR_SERVICE_START_HANG, "ERROR_SERVICE_START_HANG");
		ERROR_NAMES.put(ERROR_INVALID_SERVICE_LOCK, "ERROR_INVALID_SERVICE_LOCK");
		ERROR_NAMES.put(ERROR_SERVICE_MARKED_FOR_DELETE, "ERROR_SERVICE_MARKED_FOR_DELETE");
		ERROR_NAMES.put(ERROR_SERVICE_EXISTS, "ERROR_SERVICE_EXISTS");
		ERROR_NAMES.put(ERROR_ALREADY_RUNNING_LKG, "ERROR_ALREADY_RUNNING_LKG");
		ERROR_NAMES.put(ERROR_SERVICE_DEPENDENCY_DELETED, "ERROR_SERVICE_DEPENDENCY_DELETED");
		ERROR_NAMES.put(ERROR_BOOT_ALREADY_ACCEPTED, "ERROR_BOOT_ALREADY_ACCEPTED");
		ERROR_NAMES.put(ERROR_SERVICE_NEVER_STARTED, "ERROR_SERVICE_NEVER_STARTED");
		ERROR_NAMES.put(ERROR_DUPLICATE_SERVICE_NAME, "ERROR_DUPLICATE_SERVICE_NAME");
		ERROR_NAMES.put(ERROR_DIFFERENT_SERVICE_ACCOUNT, "ERROR_DIFFERENT_SERVICE_ACCOUNT");
		ERROR_NAMES.put(ERROR_CANNOT_DETECT_DRIVER_FAILURE, "ERROR_CANNOT_DETECT_DRIVER_FAILURE");
		ERROR_NAMES.put(ERROR_CANNOT_DETECT_PROCESS_ABORT, "ERROR_CANNOT_DETECT_PROCESS_ABORT");
		ERROR_NAMES.put(ERROR_NO_RECOVERY_PROGRAM, "ERROR_NO_RECOVERY_PROGRAM");
		ERROR_NAMES.put(ERROR_SERVICE_NOT_IN_EXE, "ERROR_SERVICE_NOT_IN_EXE");
		ERROR_NAMES.put(ERROR_NOT_SAFEBOOT_SERVICE, "ERROR_NOT_SAFEBOOT_SERVICE");
		ERROR_NAMES.put(ERROR_END_OF_MEDIA, "ERROR_END_OF_MEDIA");
		ERROR_NAMES.put(ERROR_FILEMARK_DETECTED, "ERROR_FILEMARK_DETECTED");
		ERROR_NAMES.put(ERROR_BEGINNING_OF_MEDIA, "ERROR_BEGINNING_OF_MEDIA");
		ERROR_NAMES.put(ERROR_SETMARK_DETECTED, "ERROR_SETMARK_DETECTED");
		ERROR_NAMES.put(ERROR_NO_DATA_DETECTED, "ERROR_NO_DATA_DETECTED");
		ERROR_NAMES.put(ERROR_PARTITION_FAILURE, "ERROR_PARTITION_FAILURE");
		ERROR_NAMES.put(ERROR_INVALID_BLOCK_LENGTH, "ERROR_INVALID_BLOCK_LENGTH");
		ERROR_NAMES.put(ERROR_DEVICE_NOT_PARTITIONED, "ERROR_DEVICE_NOT_PARTITIONED");
		ERROR_NAMES.put(ERROR_UNABLE_TO_LOCK_MEDIA, "ERROR_UNABLE_TO_LOCK_MEDIA");
		ERROR_NAMES.put(ERROR_UNABLE_TO_UNLOAD_MEDIA, "ERROR_UNABLE_TO_UNLOAD_MEDIA");
		ERROR_NAMES.put(ERROR_MEDIA_CHANGED, "ERROR_MEDIA_CHANGED");
		ERROR_NAMES.put(ERROR_BUS_RESET, "ERROR_BUS_RESET");
		ERROR_NAMES.put(ERROR_NO_MEDIA_IN_DRIVE, "ERROR_NO_MEDIA_IN_DRIVE");
		ERROR_NAMES.put(ERROR_NO_UNICODE_TRANSLATION, "ERROR_NO_UNICODE_TRANSLATION");
		ERROR_NAMES.put(ERROR_DLL_INIT_FAILED, "ERROR_DLL_INIT_FAILED");
		ERROR_NAMES.put(ERROR_SHUTDOWN_IN_PROGRESS, "ERROR_SHUTDOWN_IN_PROGRESS");
		ERROR_NAMES.put(ERROR_NO_SHUTDOWN_IN_PROGRESS, "ERROR_NO_SHUTDOWN_IN_PROGRESS");
		ERROR_NAMES.put(ERROR_IO_DEVICE, "ERROR_IO_DEVICE");
		ERROR_NAMES.put(ERROR_SERIAL_NO_DEVICE, "ERROR_SERIAL_NO_DEVICE");
		ERROR_NAMES.put(ERROR_IRQ_BUSY, "ERROR_IRQ_BUSY");
		ERROR_NAMES.put(ERROR_MORE_WRITES, "ERROR_MORE_WRITES");
		ERROR_NAMES.put(ERROR_COUNTER_TIMEOUT, "ERROR_COUNTER_TIMEOUT");
		ERROR_NAMES.put(ERROR_FLOPPY_ID_MARK_NOT_FOUND, "ERROR_FLOPPY_ID_MARK_NOT_FOUND");
		ERROR_NAMES.put(ERROR_FLOPPY_WRONG_CYLINDER, "ERROR_FLOPPY_WRONG_CYLINDER");
		ERROR_NAMES.put(ERROR_FLOPPY_UNKNOWN_ERROR, "ERROR_FLOPPY_UNKNOWN_ERROR");
		ERROR_NAMES.put(ERROR_FLOPPY_BAD_REGISTERS, "ERROR_FLOPPY_BAD_REGISTERS");
		ERROR_NAMES.put(ERROR_DISK_RECALIBRATE_FAILED, "ERROR_DISK_RECALIBRATE_FAILED");
		ERROR_NAMES.put(ERROR_DISK_OPERATION_FAILED, "ERROR_DISK_OPERATION_FAILED");
		ERROR_NAMES.put(ERROR_DISK_RESET_FAILED, "ERROR_DISK_RESET_FAILED");
		ERROR_NAMES.put(ERROR_EOM_OVERFLOW, "ERROR_EOM_OVERFLOW");
		ERROR_NAMES.put(ERROR_NOT_ENOUGH_SERVER_MEMORY, "ERROR_NOT_ENOUGH_SERVER_MEMORY");
		ERROR_NAMES.put(ERROR_POSSIBLE_DEADLOCK, "ERROR_POSSIBLE_DEADLOCK");
		ERROR_NAMES.put(ERROR_MAPPED_ALIGNMENT, "ERROR_MAPPED_ALIGNMENT");
		ERROR_NAMES.put(ERROR_SET_POWER_STATE_VETOED, "ERROR_SET_POWER_STATE_VETOED");
		ERROR_NAMES.put(ERROR_SET_POWER_STATE_FAILED, "ERROR_SET_POWER_STATE_FAILED");
		ERROR_NAMES.put(ERROR_TOO_MANY_LINKS, "ERROR_TOO_MANY_LINKS");
		ERROR_NAMES.put(ERROR_OLD_WIN_VERSION, "ERROR_OLD_WIN_VERSION");
		ERROR_NAMES.put(ERROR_APP_WRONG_OS, "ERROR_APP_WRONG_OS");
		ERROR_NAMES.put(ERROR_SINGLE_INSTANCE_APP, "ERROR_SINGLE_INSTANCE_APP");
		ERROR_NAMES.put(ERROR_RMODE_APP, "ERROR_RMODE_APP");
		ERROR_NAMES.put(ERROR_INVALID_DLL, "ERROR_INVALID_DLL");
		ERROR_NAMES.put(ERROR_NO_ASSOCIATION, "ERROR_NO_ASSOCIATION");
		ERROR_NAMES.put(ERROR_DDE_FAIL, "ERROR_DDE_FAIL");
		ERROR_NAMES.put(ERROR_DLL_NOT_FOUND, "ERROR_DLL_NOT_FOUND");
		ERROR_NAMES.put(ERROR_NO_MORE_USER_HANDLES, "ERROR_NO_MORE_USER_HANDLES");
		ERROR_NAMES.put(ERROR_MESSAGE_SYNC_ONLY, "ERROR_MESSAGE_SYNC_ONLY");
		ERROR_NAMES.put(ERROR_SOURCE_ELEMENT_EMPTY, "ERROR_SOURCE_ELEMENT_EMPTY");
		ERROR_NAMES.put(ERROR_DESTINATION_ELEMENT_FULL, "ERROR_DESTINATION_ELEMENT_FULL");
		ERROR_NAMES.put(ERROR_ILLEGAL_ELEMENT_ADDRESS, "ERROR_ILLEGAL_ELEMENT_ADDRESS");
		ERROR_NAMES.put(ERROR_MAGAZINE_NOT_PRESENT, "ERROR_MAGAZINE_NOT_PRESENT");
		ERROR_NAMES.put(ERROR_DEVICE_REINITIALIZATION_NEEDED, "ERROR_DEVICE_REINITIALIZATION_NEEDED");
		ERROR_NAMES.put(ERROR_DEVICE_REQUIRES_CLEANING, "ERROR_DEVICE_REQUIRES_CLEANING");
		ERROR_NAMES.put(ERROR_DEVICE_DOOR_OPEN, "ERROR_DEVICE_DOOR_OPEN");
		ERROR_NAMES.put(ERROR_DEVICE_NOT_CONNECTED, "ERROR_DEVICE_NOT_CONNECTED");
		ERROR_NAMES.put(ERROR_NOT_FOUND, "ERROR_NOT_FOUND");
		ERROR_NAMES.put(ERROR_NO_MATCH, "ERROR_NO_MATCH");
		ERROR_NAMES.put(ERROR_SET_NOT_FOUND, "ERROR_SET_NOT_FOUND");
		ERROR_NAMES.put(ERROR_POINT_NOT_FOUND, "ERROR_POINT_NOT_FOUND");
		ERROR_NAMES.put(ERROR_NO_TRACKING_SERVICE, "ERROR_NO_TRACKING_SERVICE");
		ERROR_NAMES.put(ERROR_NO_VOLUME_ID, "ERROR_NO_VOLUME_ID");
		ERROR_NAMES.put(ERROR_UNABLE_TO_REMOVE_REPLACED, "ERROR_UNABLE_TO_REMOVE_REPLACED");
		ERROR_NAMES.put(ERROR_UNABLE_TO_MOVE_REPLACEMENT, "ERROR_UNABLE_TO_MOVE_REPLACEMENT");
		ERROR_NAMES.put(ERROR_UNABLE_TO_MOVE_REPLACEMENT_2, "ERROR_UNABLE_TO_MOVE_REPLACEMENT_2");
		ERROR_NAMES.put(ERROR_JOURNAL_DELETE_IN_PROGRESS, "ERROR_JOURNAL_DELETE_IN_PROGRESS");
		ERROR_NAMES.put(ERROR_JOURNAL_NOT_ACTIVE, "ERROR_JOURNAL_NOT_ACTIVE");
		ERROR_NAMES.put(ERROR_POTENTIAL_FILE_FOUND, "ERROR_POTENTIAL_FILE_FOUND");
		ERROR_NAMES.put(ERROR_JOURNAL_ENTRY_DELETED, "ERROR_JOURNAL_ENTRY_DELETED");
		ERROR_NAMES.put(ERROR_BAD_DEVICE, "ERROR_BAD_DEVICE");
		ERROR_NAMES.put(ERROR_CONNECTION_UNAVAIL, "ERROR_CONNECTION_UNAVAIL");
		ERROR_NAMES.put(ERROR_DEVICE_ALREADY_REMEMBERED, "ERROR_DEVICE_ALREADY_REMEMBERED");
		ERROR_NAMES.put(ERROR_NO_NET_OR_BAD_PATH, "ERROR_NO_NET_OR_BAD_PATH");
		ERROR_NAMES.put(ERROR_BAD_PROVIDER, "ERROR_BAD_PROVIDER");
		ERROR_NAMES.put(ERROR_CANNOT_OPEN_PROFILE, "ERROR_CANNOT_OPEN_PROFILE");
		ERROR_NAMES.put(ERROR_BAD_PROFILE, "ERROR_BAD_PROFILE");
		ERROR_NAMES.put(ERROR_NOT_CONTAINER, "ERROR_NOT_CONTAINER");
		ERROR_NAMES.put(ERROR_EXTENDED_ERROR, "ERROR_EXTENDED_ERROR");
		ERROR_NAMES.put(ERROR_INVALID_GROUPNAME, "ERROR_INVALID_GROUPNAME");
		ERROR_NAMES.put(ERROR_INVALID_COMPUTERNAME, "ERROR_INVALID_COMPUTERNAME");
		ERROR_NAMES.put(ERROR_INVALID_EVENTNAME, "ERROR_INVALID_EVENTNAME");
		ERROR_NAMES.put(ERROR_INVALID_DOMAINNAME, "ERROR_INVALID_DOMAINNAME");
		ERROR_NAMES.put(ERROR_INVALID_SERVICENAME, "ERROR_INVALID_SERVICENAME");
		ERROR_NAMES.put(ERROR_INVALID_NETNAME, "ERROR_INVALID_NETNAME");
		ERROR_NAMES.put(ERROR_INVALID_SHARENAME, "ERROR_INVALID_SHARENAME");
		ERROR_NAMES.put(ERROR_INVALID_PASSWORDNAME, "ERROR_INVALID_PASSWORDNAME");
		ERROR_NAMES.put(ERROR_INVALID_MESSAGENAME, "ERROR_INVALID_MESSAGENAME");
		ERROR_NAMES.put(ERROR_INVALID_MESSAGEDEST, "ERROR_INVALID_MESSAGEDEST");
		ERROR_NAMES.put(ERROR_SESSION_CREDENTIAL_CONFLICT, "ERROR_SESSION_CREDENTIAL_CONFLICT");
		ERROR_NAMES.put(ERROR_REMOTE_SESSION_LIMIT_EXCEEDED, "ERROR_REMOTE_SESSION_LIMIT_EXCEEDED");
		ERROR_NAMES.put(ERROR_DUP_DOMAINNAME, "ERROR_DUP_DOMAINNAME");
		ERROR_NAMES.put(ERROR_NO_NETWORK, "ERROR_NO_NETWORK");
		ERROR_NAMES.put(ERROR_CANCELLED, "ERROR_CANCELLED");
		ERROR_NAMES.put(ERROR_USER_MAPPED_FILE, "ERROR_USER_MAPPED_FILE");
		ERROR_NAMES.put(ERROR_CONNECTION_REFUSED, "ERROR_CONNECTION_REFUSED");
		ERROR_NAMES.put(ERROR_GRACEFUL_DISCONNECT, "ERROR_GRACEFUL_DISCONNECT");
		ERROR_NAMES.put(ERROR_ADDRESS_ALREADY_ASSOCIATED, "ERROR_ADDRESS_ALREADY_ASSOCIATED");
		ERROR_NAMES.put(ERROR_ADDRESS_NOT_ASSOCIATED, "ERROR_ADDRESS_NOT_ASSOCIATED");
		ERROR_NAMES.put(ERROR_CONNECTION_INVALID, "ERROR_CONNECTION_INVALID");
		ERROR_NAMES.put(ERROR_CONNECTION_ACTIVE, "ERROR_CONNECTION_ACTIVE");
		ERROR_NAMES.put(ERROR_NETWORK_UNREACHABLE, "ERROR_NETWORK_UNREACHABLE");
		ERROR_NAMES.put(ERROR_HOST_UNREACHABLE, "ERROR_HOST_UNREACHABLE");
		ERROR_NAMES.put(ERROR_PROTOCOL_UNREACHABLE, "ERROR_PROTOCOL_UNREACHABLE");
		ERROR_NAMES.put(ERROR_PORT_UNREACHABLE, "ERROR_PORT_UNREACHABLE");
		ERROR_NAMES.put(ERROR_REQUEST_ABORTED, "ERROR_REQUEST_ABORTED");
		ERROR_NAMES.put(ERROR_CONNECTION_ABORTED, "ERROR_CONNECTION_ABORTED");
		ERROR_NAMES.put(ERROR_RETRY, "ERROR_RETRY");
		ERROR_NAMES.put(ERROR_CONNECTION_COUNT_LIMIT, "ERROR_CONNECTION_COUNT_LIMIT");
		ERROR_NAMES.put(ERROR_LOGIN_TIME_RESTRICTION, "ERROR_LOGIN_TIME_RESTRICTION");
		ERROR_NAMES.put(ERROR_LOGIN_WKSTA_RESTRICTION, "ERROR_LOGIN_WKSTA_RESTRICTION");
		ERROR_NAMES.put(ERROR_INCORRECT_ADDRESS, "ERROR_INCORRECT_ADDRESS");
		ERROR_NAMES.put(ERROR_ALREADY_REGISTERED, "ERROR_ALREADY_REGISTERED");
		ERROR_NAMES.put(ERROR_SERVICE_NOT_FOUND, "ERROR_SERVICE_NOT_FOUND");
		ERROR_NAMES.put(ERROR_NOT_AUTHENTICATED, "ERROR_NOT_AUTHENTICATED");
		ERROR_NAMES.put(ERROR_NOT_LOGGED_ON, "ERROR_NOT_LOGGED_ON");
		ERROR_NAMES.put(ERROR_CONTINUE, "ERROR_CONTINUE");
		ERROR_NAMES.put(ERROR_ALREADY_INITIALIZED, "ERROR_ALREADY_INITIALIZED");
		ERROR_NAMES.put(ERROR_NO_MORE_DEVICES, "ERROR_NO_MORE_DEVICES");
		ERROR_NAMES.put(ERROR_NO_SUCH_SITE, "ERROR_NO_SUCH_SITE");
		ERROR_NAMES.put(ERROR_DOMAIN_CONTROLLER_EXISTS, "ERROR_DOMAIN_CONTROLLER_EXISTS");
		ERROR_NAMES.put(ERROR_ONLY_IF_CONNECTED, "ERROR_ONLY_IF_CONNECTED");
		ERROR_NAMES.put(ERROR_OVERRIDE_NOCHANGES, "ERROR_OVERRIDE_NOCHANGES");
		ERROR_NAMES.put(ERROR_BAD_USER_PROFILE, "ERROR_BAD_USER_PROFILE");
		ERROR_NAMES.put(ERROR_NOT_SUPPORTED_ON_SBS, "ERROR_NOT_SUPPORTED_ON_SBS");
		ERROR_NAMES.put(ERROR_SERVER_SHUTDOWN_IN_PROGRESS, "ERROR_SERVER_SHUTDOWN_IN_PROGRESS");
		ERROR_NAMES.put(ERROR_HOST_DOWN, "ERROR_HOST_DOWN");
		ERROR_NAMES.put(ERROR_NON_ACCOUNT_SID, "ERROR_NON_ACCOUNT_SID");
		ERROR_NAMES.put(ERROR_NON_DOMAIN_SID, "ERROR_NON_DOMAIN_SID");
		ERROR_NAMES.put(ERROR_APPHELP_BLOCK, "ERROR_APPHELP_BLOCK");
		ERROR_NAMES.put(ERROR_ACCESS_DISABLED_BY_POLICY, "ERROR_ACCESS_DISABLED_BY_POLICY");
		ERROR_NAMES.put(ERROR_REG_NAT_CONSUMPTION, "ERROR_REG_NAT_CONSUMPTION");
		ERROR_NAMES.put(ERROR_CSCSHARE_OFFLINE, "ERROR_CSCSHARE_OFFLINE");
		ERROR_NAMES.put(ERROR_PKINIT_FAILURE, "ERROR_PKINIT_FAILURE");
		ERROR_NAMES.put(ERROR_SMARTCARD_SUBSYSTEM_FAILURE, "ERROR_SMARTCARD_SUBSYSTEM_FAILURE");
		ERROR_NAMES.put(ERROR_DOWNGRADE_DETECTED, "ERROR_DOWNGRADE_DETECTED");
		ERROR_NAMES.put(ERROR_MACHINE_LOCKED, "ERROR_MACHINE_LOCKED");
		ERROR_NAMES.put(ERROR_CALLBACK_SUPPLIED_INVALID_DATA, "ERROR_CALLBACK_SUPPLIED_INVALID_DATA");
		ERROR_NAMES.put(ERROR_SYNC_FOREGROUND_REFRESH_REQUIRED, "ERROR_SYNC_FOREGROUND_REFRESH_REQUIRED");
		ERROR_NAMES.put(ERROR_DRIVER_BLOCKED, "ERROR_DRIVER_BLOCKED");
		ERROR_NAMES.put(ERROR_INVALID_IMPORT_OF_NON_DLL, "ERROR_INVALID_IMPORT_OF_NON_DLL");
		ERROR_NAMES.put(ERROR_ACCESS_DISABLED_WEBBLADE, "ERROR_ACCESS_DISABLED_WEBBLADE");
		ERROR_NAMES.put(ERROR_ACCESS_DISABLED_WEBBLADE_TAMPER, "ERROR_ACCESS_DISABLED_WEBBLADE_TAMPER");
		ERROR_NAMES.put(ERROR_RECOVERY_FAILURE, "ERROR_RECOVERY_FAILURE");
		ERROR_NAMES.put(ERROR_ALREADY_FIBER, "ERROR_ALREADY_FIBER");
		ERROR_NAMES.put(ERROR_ALREADY_THREAD, "ERROR_ALREADY_THREAD");
		ERROR_NAMES.put(ERROR_STACK_BUFFER_OVERRUN, "ERROR_STACK_BUFFER_OVERRUN");
		ERROR_NAMES.put(ERROR_PARAMETER_QUOTA_EXCEEDED, "ERROR_PARAMETER_QUOTA_EXCEEDED");
		ERROR_NAMES.put(ERROR_DEBUGGER_INACTIVE, "ERROR_DEBUGGER_INACTIVE");
		ERROR_NAMES.put(ERROR_DELAY_LOAD_FAILED, "ERROR_DELAY_LOAD_FAILED");
		ERROR_NAMES.put(ERROR_VDM_DISALLOWED, "ERROR_VDM_DISALLOWED");
		ERROR_NAMES.put(ERROR_UNIDENTIFIED_ERROR, "ERROR_UNIDENTIFIED_ERROR");
		ERROR_NAMES.put(ERROR_NOT_ALL_ASSIGNED, "ERROR_NOT_ALL_ASSIGNED");
		ERROR_NAMES.put(ERROR_SOME_NOT_MAPPED, "ERROR_SOME_NOT_MAPPED");
		ERROR_NAMES.put(ERROR_NO_QUOTAS_FOR_ACCOUNT, "ERROR_NO_QUOTAS_FOR_ACCOUNT");
		ERROR_NAMES.put(ERROR_LOCAL_USER_SESSION_KEY, "ERROR_LOCAL_USER_SESSION_KEY");
		ERROR_NAMES.put(ERROR_NULL_LM_PASSWORD, "ERROR_NULL_LM_PASSWORD");
		ERROR_NAMES.put(ERROR_UNKNOWN_REVISION, "ERROR_UNKNOWN_REVISION");
		ERROR_NAMES.put(ERROR_REVISION_MISMATCH, "ERROR_REVISION_MISMATCH");
		ERROR_NAMES.put(ERROR_INVALID_OWNER, "ERROR_INVALID_OWNER");
		ERROR_NAMES.put(ERROR_INVALID_PRIMARY_GROUP, "ERROR_INVALID_PRIMARY_GROUP");
		ERROR_NAMES.put(ERROR_NO_IMPERSONATION_TOKEN, "ERROR_NO_IMPERSONATION_TOKEN");
		ERROR_NAMES.put(ERROR_CANT_DISABLE_MANDATORY, "ERROR_CANT_DISABLE_MANDATORY");
		ERROR_NAMES.put(ERROR_NO_LOGON_SERVERS, "ERROR_NO_LOGON_SERVERS");
		ERROR_NAMES.put(ERROR_NO_SUCH_LOGON_SESSION, "ERROR_NO_SUCH_LOGON_SESSION");
		ERROR_NAMES.put(ERROR_NO_SUCH_PRIVILEGE, "ERROR_NO_SUCH_PRIVILEGE");
		ERROR_NAMES.put(ERROR_PRIVILEGE_NOT_HELD, "ERROR_PRIVILEGE_NOT_HELD");
		ERROR_NAMES.put(ERROR_INVALID_ACCOUNT_NAME, "ERROR_INVALID_ACCOUNT_NAME");
		ERROR_NAMES.put(ERROR_USER_EXISTS, "ERROR_USER_EXISTS");
		ERROR_NAMES.put(ERROR_NO_SUCH_USER, "ERROR_NO_SUCH_USER");
		ERROR_NAMES.put(ERROR_GROUP_EXISTS, "ERROR_GROUP_EXISTS");
		ERROR_NAMES.put(ERROR_NO_SUCH_GROUP, "ERROR_NO_SUCH_GROUP");
		ERROR_NAMES.put(ERROR_MEMBER_IN_GROUP, "ERROR_MEMBER_IN_GROUP");
		ERROR_NAMES.put(ERROR_MEMBER_NOT_IN_GROUP, "ERROR_MEMBER_NOT_IN_GROUP");
		ERROR_NAMES.put(ERROR_LAST_ADMIN, "ERROR_LAST_ADMIN");
		ERROR_NAMES.put(ERROR_WRONG_PASSWORD, "ERROR_WRONG_PASSWORD");
		ERROR_NAMES.put(ERROR_ILL_FORMED_PASSWORD, "ERROR_ILL_FORMED_PASSWORD");
		ERROR_NAMES.put(ERROR_PASSWORD_RESTRICTION, "ERROR_PASSWORD_RESTRICTION");
		ERROR_NAMES.put(ERROR_LOGON_FAILURE, "ERROR_LOGON_FAILURE");
		ERROR_NAMES.put(ERROR_ACCOUNT_RESTRICTION, "ERROR_ACCOUNT_RESTRICTION");
		ERROR_NAMES.put(ERROR_INVALID_LOGON_HOURS, "ERROR_INVALID_LOGON_HOURS");
		ERROR_NAMES.put(ERROR_INVALID_WORKSTATION, "ERROR_INVALID_WORKSTATION");
		ERROR_NAMES.put(ERROR_PASSWORD_EXPIRED, "ERROR_PASSWORD_EXPIRED");
		ERROR_NAMES.put(ERROR_ACCOUNT_DISABLED, "ERROR_ACCOUNT_DISABLED");
		ERROR_NAMES.put(ERROR_NONE_MAPPED, "ERROR_NONE_MAPPED");
		ERROR_NAMES.put(ERROR_TOO_MANY_LUIDS_REQUESTED, "ERROR_TOO_MANY_LUIDS_REQUESTED");
		ERROR_NAMES.put(ERROR_LUIDS_EXHAUSTED, "ERROR_LUIDS_EXHAUSTED");
		ERROR_NAMES.put(ERROR_INVALID_SUB_AUTHORITY, "ERROR_INVALID_SUB_AUTHORITY");
		ERROR_NAMES.put(ERROR_INVALID_ACL, "ERROR_INVALID_ACL");
		ERROR_NAMES.put(ERROR_INVALID_SID, "ERROR_INVALID_SID");
		ERROR_NAMES.put(ERROR_INVALID_SECURITY_DESCR, "ERROR_INVALID_SECURITY_DESCR");
		ERROR_NAMES.put(ERROR_BAD_INHERITANCE_ACL, "ERROR_BAD_INHERITANCE_ACL");
		ERROR_NAMES.put(ERROR_SERVER_DISABLED, "ERROR_SERVER_DISABLED");
		ERROR_NAMES.put(ERROR_SERVER_NOT_DISABLED, "ERROR_SERVER_NOT_DISABLED");
		ERROR_NAMES.put(ERROR_INVALID_ID_AUTHORITY, "ERROR_INVALID_ID_AUTHORITY");
		ERROR_NAMES.put(ERROR_ALLOTTED_SPACE_EXCEEDED, "ERROR_ALLOTTED_SPACE_EXCEEDED");
		ERROR_NAMES.put(ERROR_INVALID_GROUP_ATTRIBUTES, "ERROR_INVALID_GROUP_ATTRIBUTES");
		ERROR_NAMES.put(ERROR_BAD_IMPERSONATION_LEVEL, "ERROR_BAD_IMPERSONATION_LEVEL");
		ERROR_NAMES.put(ERROR_CANT_OPEN_ANONYMOUS, "ERROR_CANT_OPEN_ANONYMOUS");
		ERROR_NAMES.put(ERROR_BAD_VALIDATION_CLASS, "ERROR_BAD_VALIDATION_CLASS");
		ERROR_NAMES.put(ERROR_BAD_TOKEN_TYPE, "ERROR_BAD_TOKEN_TYPE");
		ERROR_NAMES.put(ERROR_NO_SECURITY_ON_OBJECT, "ERROR_NO_SECURITY_ON_OBJECT");
		ERROR_NAMES.put(ERROR_CANT_ACCESS_DOMAIN_INFO, "ERROR_CANT_ACCESS_DOMAIN_INFO");
		ERROR_NAMES.put(ERROR_INVALID_SERVER_STATE, "ERROR_INVALID_SERVER_STATE");
		ERROR_NAMES.put(ERROR_INVALID_DOMAIN_STATE, "ERROR_INVALID_DOMAIN_STATE");
		ERROR_NAMES.put(ERROR_INVALID_DOMAIN_ROLE, "ERROR_INVALID_DOMAIN_ROLE");
		ERROR_NAMES.put(ERROR_NO_SUCH_DOMAIN, "ERROR_NO_SUCH_DOMAIN");
		ERROR_NAMES.put(ERROR_DOMAIN_EXISTS, "ERROR_DOMAIN_EXISTS");
		ERROR_NAMES.put(ERROR_DOMAIN_LIMIT_EXCEEDED, "ERROR_DOMAIN_LIMIT_EXCEEDED");
		ERROR_NAMES.put(ERROR_INTERNAL_DB_CORRUPTION, "ERROR_INTERNAL_DB_CORRUPTION");
		ERROR_NAMES.put(ERROR_INTERNAL_ERROR, "ERROR_INTERNAL_ERROR");
		ERROR_NAMES.put(ERROR_GENERIC_NOT_MAPPED, "ERROR_GENERIC_NOT_MAPPED");
		ERROR_NAMES.put(ERROR_BAD_DESCRIPTOR_FORMAT, "ERROR_BAD_DESCRIPTOR_FORMAT");
		ERROR_NAMES.put(ERROR_NOT_LOGON_PROCESS, "ERROR_NOT_LOGON_PROCESS");
		ERROR_NAMES.put(ERROR_LOGON_SESSION_EXISTS, "ERROR_LOGON_SESSION_EXISTS");
		ERROR_NAMES.put(ERROR_NO_SUCH_PACKAGE, "ERROR_NO_SUCH_PACKAGE");
		ERROR_NAMES.put(ERROR_BAD_LOGON_SESSION_STATE, "ERROR_BAD_LOGON_SESSION_STATE");
		ERROR_NAMES.put(ERROR_LOGON_SESSION_COLLISION, "ERROR_LOGON_SESSION_COLLISION");
		ERROR_NAMES.put(ERROR_INVALID_LOGON_TYPE, "ERROR_INVALID_LOGON_TYPE");
		ERROR_NAMES.put(ERROR_CANNOT_IMPERSONATE, "ERROR_CANNOT_IMPERSONATE");
		ERROR_NAMES.put(ERROR_RXACT_INVALID_STATE, "ERROR_RXACT_INVALID_STATE");
		ERROR_NAMES.put(ERROR_RXACT_COMMIT_FAILURE, "ERROR_RXACT_COMMIT_FAILURE");
		ERROR_NAMES.put(ERROR_SPECIAL_ACCOUNT, "ERROR_SPECIAL_ACCOUNT");
		ERROR_NAMES.put(ERROR_SPECIAL_GROUP, "ERROR_SPECIAL_GROUP");
		ERROR_NAMES.put(ERROR_SPECIAL_USER, "ERROR_SPECIAL_USER");
		ERROR_NAMES.put(ERROR_MEMBERS_PRIMARY_GROUP, "ERROR_MEMBERS_PRIMARY_GROUP");
		ERROR_NAMES.put(ERROR_TOKEN_ALREADY_IN_USE, "ERROR_TOKEN_ALREADY_IN_USE");
		ERROR_NAMES.put(ERROR_NO_SUCH_ALIAS, "ERROR_NO_SUCH_ALIAS");
		ERROR_NAMES.put(ERROR_MEMBER_NOT_IN_ALIAS, "ERROR_MEMBER_NOT_IN_ALIAS");
		ERROR_NAMES.put(ERROR_MEMBER_IN_ALIAS, "ERROR_MEMBER_IN_ALIAS");
		ERROR_NAMES.put(ERROR_ALIAS_EXISTS, "ERROR_ALIAS_EXISTS");
		ERROR_NAMES.put(ERROR_LOGON_NOT_GRANTED, "ERROR_LOGON_NOT_GRANTED");
		ERROR_NAMES.put(ERROR_TOO_MANY_SECRETS, "ERROR_TOO_MANY_SECRETS");
		ERROR_NAMES.put(ERROR_SECRET_TOO_LONG, "ERROR_SECRET_TOO_LONG");
		ERROR_NAMES.put(ERROR_INTERNAL_DB_ERROR, "ERROR_INTERNAL_DB_ERROR");
		ERROR_NAMES.put(ERROR_TOO_MANY_CONTEXT_IDS, "ERROR_TOO_MANY_CONTEXT_IDS");
		ERROR_NAMES.put(ERROR_LOGON_TYPE_NOT_GRANTED, "ERROR_LOGON_TYPE_NOT_GRANTED");
		ERROR_NAMES.put(ERROR_NT_CROSS_ENCRYPTION_REQUIRED, "ERROR_NT_CROSS_ENCRYPTION_REQUIRED");
		ERROR_NAMES.put(ERROR_NO_SUCH_MEMBER, "ERROR_NO_SUCH_MEMBER");
		ERROR_NAMES.put(ERROR_INVALID_MEMBER, "ERROR_INVALID_MEMBER");
		ERROR_NAMES.put(ERROR_TOO_MANY_SIDS, "ERROR_TOO_MANY_SIDS");
		ERROR_NAMES.put(ERROR_LM_CROSS_ENCRYPTION_REQUIRED, "ERROR_LM_CROSS_ENCRYPTION_REQUIRED");
		ERROR_NAMES.put(ERROR_NO_INHERITANCE, "ERROR_NO_INHERITANCE");
		ERROR_NAMES.put(ERROR_FILE_CORRUPT, "ERROR_FILE_CORRUPT");
		ERROR_NAMES.put(ERROR_DISK_CORRUPT, "ERROR_DISK_CORRUPT");
		ERROR_NAMES.put(ERROR_NO_USER_SESSION_KEY, "ERROR_NO_USER_SESSION_KEY");
		ERROR_NAMES.put(ERROR_LICENSE_QUOTA_EXCEEDED, "ERROR_LICENSE_QUOTA_EXCEEDED");
		ERROR_NAMES.put(ERROR_WRONG_TARGET_NAME, "ERROR_WRONG_TARGET_NAME");
		ERROR_NAMES.put(ERROR_MUTUAL_AUTH_FAILED, "ERROR_MUTUAL_AUTH_FAILED");
		ERROR_NAMES.put(ERROR_TIME_SKEW, "ERROR_TIME_SKEW");
		ERROR_NAMES.put(ERROR_CURRENT_DOMAIN_NOT_ALLOWED, "ERROR_CURRENT_DOMAIN_NOT_ALLOWED");
		ERROR_NAMES.put(ERROR_INVALID_WINDOW_HANDLE, "ERROR_INVALID_WINDOW_HANDLE");
		ERROR_NAMES.put(ERROR_INVALID_MENU_HANDLE, "ERROR_INVALID_MENU_HANDLE");
		ERROR_NAMES.put(ERROR_INVALID_CURSOR_HANDLE, "ERROR_INVALID_CURSOR_HANDLE");
		ERROR_NAMES.put(ERROR_INVALID_ACCEL_HANDLE, "ERROR_INVALID_ACCEL_HANDLE");
		ERROR_NAMES.put(ERROR_INVALID_HOOK_HANDLE, "ERROR_INVALID_HOOK_HANDLE");
		ERROR_NAMES.put(ERROR_INVALID_DWP_HANDLE, "ERROR_INVALID_DWP_HANDLE");
		ERROR_NAMES.put(ERROR_TLW_WITH_WSCHILD, "ERROR_TLW_WITH_WSCHILD");
		ERROR_NAMES.put(ERROR_CANNOT_FIND_WND_CLASS, "ERROR_CANNOT_FIND_WND_CLASS");
		ERROR_NAMES.put(ERROR_WINDOW_OF_OTHER_THREAD, "ERROR_WINDOW_OF_OTHER_THREAD");
		ERROR_NAMES.put(ERROR_HOTKEY_ALREADY_REGISTERED, "ERROR_HOTKEY_ALREADY_REGISTERED");
		ERROR_NAMES.put(ERROR_CLASS_ALREADY_EXISTS, "ERROR_CLASS_ALREADY_EXISTS");
		ERROR_NAMES.put(ERROR_CLASS_DOES_NOT_EXIST, "ERROR_CLASS_DOES_NOT_EXIST");
		ERROR_NAMES.put(ERROR_CLASS_HAS_WINDOWS, "ERROR_CLASS_HAS_WINDOWS");
		ERROR_NAMES.put(ERROR_INVALID_INDEX, "ERROR_INVALID_INDEX");
		ERROR_NAMES.put(ERROR_INVALID_ICON_HANDLE, "ERROR_INVALID_ICON_HANDLE");
		ERROR_NAMES.put(ERROR_PRIVATE_DIALOG_INDEX, "ERROR_PRIVATE_DIALOG_INDEX");
		ERROR_NAMES.put(ERROR_LISTBOX_ID_NOT_FOUND, "ERROR_LISTBOX_ID_NOT_FOUND");
		ERROR_NAMES.put(ERROR_NO_WILDCARD_CHARACTERS, "ERROR_NO_WILDCARD_CHARACTERS");
		ERROR_NAMES.put(ERROR_CLIPBOARD_NOT_OPEN, "ERROR_CLIPBOARD_NOT_OPEN");
		ERROR_NAMES.put(ERROR_HOTKEY_NOT_REGISTERED, "ERROR_HOTKEY_NOT_REGISTERED");
		ERROR_NAMES.put(ERROR_WINDOW_NOT_DIALOG, "ERROR_WINDOW_NOT_DIALOG");
		ERROR_NAMES.put(ERROR_CONTROL_ID_NOT_FOUND, "ERROR_CONTROL_ID_NOT_FOUND");
		ERROR_NAMES.put(ERROR_INVALID_COMBOBOX_MESSAGE, "ERROR_INVALID_COMBOBOX_MESSAGE");
		ERROR_NAMES.put(ERROR_WINDOW_NOT_COMBOBOX, "ERROR_WINDOW_NOT_COMBOBOX");
		ERROR_NAMES.put(ERROR_INVALID_EDIT_HEIGHT, "ERROR_INVALID_EDIT_HEIGHT");
		ERROR_NAMES.put(ERROR_DC_NOT_FOUND, "ERROR_DC_NOT_FOUND");
		ERROR_NAMES.put(ERROR_INVALID_HOOK_FILTER, "ERROR_INVALID_HOOK_FILTER");
		ERROR_NAMES.put(ERROR_INVALID_FILTER_PROC, "ERROR_INVALID_FILTER_PROC");
		ERROR_NAMES.put(ERROR_HOOK_NEEDS_HMOD, "ERROR_HOOK_NEEDS_HMOD");
		ERROR_NAMES.put(ERROR_GLOBAL_ONLY_HOOK, "ERROR_GLOBAL_ONLY_HOOK");
		ERROR_NAMES.put(ERROR_JOURNAL_HOOK_SET, "ERROR_JOURNAL_HOOK_SET");
		ERROR_NAMES.put(ERROR_HOOK_NOT_INSTALLED, "ERROR_HOOK_NOT_INSTALLED");
		ERROR_NAMES.put(ERROR_INVALID_LB_MESSAGE, "ERROR_INVALID_LB_MESSAGE");
		ERROR_NAMES.put(ERROR_SETCOUNT_ON_BAD_LB, "ERROR_SETCOUNT_ON_BAD_LB");
		ERROR_NAMES.put(ERROR_LB_WITHOUT_TABSTOPS, "ERROR_LB_WITHOUT_TABSTOPS");
		ERROR_NAMES.put(ERROR_DESTROY_OBJECT_OF_OTHER_THREAD, "ERROR_DESTROY_OBJECT_OF_OTHER_THREAD");
		ERROR_NAMES.put(ERROR_CHILD_WINDOW_MENU, "ERROR_CHILD_WINDOW_MENU");
		ERROR_NAMES.put(ERROR_NO_SYSTEM_MENU, "ERROR_NO_SYSTEM_MENU");
		ERROR_NAMES.put(ERROR_INVALID_MSGBOX_STYLE, "ERROR_INVALID_MSGBOX_STYLE");
		ERROR_NAMES.put(ERROR_INVALID_SPI_VALUE, "ERROR_INVALID_SPI_VALUE");
		ERROR_NAMES.put(ERROR_SCREEN_ALREADY_LOCKED, "ERROR_SCREEN_ALREADY_LOCKED");
		ERROR_NAMES.put(ERROR_HWNDS_HAVE_DIFF_PARENT, "ERROR_HWNDS_HAVE_DIFF_PARENT");
		ERROR_NAMES.put(ERROR_NOT_CHILD_WINDOW, "ERROR_NOT_CHILD_WINDOW");
		ERROR_NAMES.put(ERROR_INVALID_GW_COMMAND, "ERROR_INVALID_GW_COMMAND");
		ERROR_NAMES.put(ERROR_INVALID_THREAD_ID, "ERROR_INVALID_THREAD_ID");
		ERROR_NAMES.put(ERROR_NON_MDICHILD_WINDOW, "ERROR_NON_MDICHILD_WINDOW");
		ERROR_NAMES.put(ERROR_POPUP_ALREADY_ACTIVE, "ERROR_POPUP_ALREADY_ACTIVE");
		ERROR_NAMES.put(ERROR_NO_SCROLLBARS, "ERROR_NO_SCROLLBARS");
		ERROR_NAMES.put(ERROR_INVALID_SCROLLBAR_RANGE, "ERROR_INVALID_SCROLLBAR_RANGE");
		ERROR_NAMES.put(ERROR_INVALID_SHOWWIN_COMMAND, "ERROR_INVALID_SHOWWIN_COMMAND");
		ERROR_NAMES.put(ERROR_NO_SYSTEM_RESOURCES, "ERROR_NO_SYSTEM_RESOURCES");
		ERROR_NAMES.put(ERROR_NONPAGED_SYSTEM_RESOURCES, "ERROR_NONPAGED_SYSTEM_RESOURCES");
		ERROR_NAMES.put(ERROR_PAGED_SYSTEM_RESOURCES, "ERROR_PAGED_SYSTEM_RESOURCES");
		ERROR_NAMES.put(ERROR_WORKING_SET_QUOTA, "ERROR_WORKING_SET_QUOTA");
		ERROR_NAMES.put(ERROR_PAGEFILE_QUOTA, "ERROR_PAGEFILE_QUOTA");
		ERROR_NAMES.put(ERROR_COMMITMENT_LIMIT, "ERROR_COMMITMENT_LIMIT");
		ERROR_NAMES.put(ERROR_MENU_ITEM_NOT_FOUND, "ERROR_MENU_ITEM_NOT_FOUND");
		ERROR_NAMES.put(ERROR_INVALID_KEYBOARD_HANDLE, "ERROR_INVALID_KEYBOARD_HANDLE");
		ERROR_NAMES.put(ERROR_HOOK_TYPE_NOT_ALLOWED, "ERROR_HOOK_TYPE_NOT_ALLOWED");
		ERROR_NAMES.put(ERROR_REQUIRES_INTERACTIVE_WINDOWSTATION, "ERROR_REQUIRES_INTERACTIVE_WINDOWSTATION");
		ERROR_NAMES.put(ERROR_TIMEOUT, "ERROR_TIMEOUT");
		ERROR_NAMES.put(ERROR_INVALID_MONITOR_HANDLE, "ERROR_INVALID_MONITOR_HANDLE");
		ERROR_NAMES.put(ERROR_INCORRECT_SIZE, "ERROR_INCORRECT_SIZE");
		ERROR_NAMES.put(ERROR_EVENTLOG_FILE_CORRUPT, "ERROR_EVENTLOG_FILE_CORRUPT");
		ERROR_NAMES.put(ERROR_EVENTLOG_CANT_START, "ERROR_EVENTLOG_CANT_START");
		ERROR_NAMES.put(ERROR_LOG_FILE_FULL, "ERROR_LOG_FILE_FULL");
		ERROR_NAMES.put(ERROR_EVENTLOG_FILE_CHANGED, "ERROR_EVENTLOG_FILE_CHANGED");
		ERROR_NAMES.put(ERROR_INSTALL_SERVICE_FAILURE, "ERROR_INSTALL_SERVICE_FAILURE");
		ERROR_NAMES.put(ERROR_INSTALL_USEREXIT, "ERROR_INSTALL_USEREXIT");
		ERROR_NAMES.put(ERROR_INSTALL_FAILURE, "ERROR_INSTALL_FAILURE");
		ERROR_NAMES.put(ERROR_INSTALL_SUSPEND, "ERROR_INSTALL_SUSPEND");
		ERROR_NAMES.put(ERROR_UNKNOWN_PRODUCT, "ERROR_UNKNOWN_PRODUCT");
		ERROR_NAMES.put(ERROR_UNKNOWN_FEATURE, "ERROR_UNKNOWN_FEATURE");
		ERROR_NAMES.put(ERROR_UNKNOWN_COMPONENT, "ERROR_UNKNOWN_COMPONENT");
		ERROR_NAMES.put(ERROR_UNKNOWN_PROPERTY, "ERROR_UNKNOWN_PROPERTY");
		ERROR_NAMES.put(ERROR_INVALID_HANDLE_STATE, "ERROR_INVALID_HANDLE_STATE");
		ERROR_NAMES.put(ERROR_BAD_CONFIGURATION, "ERROR_BAD_CONFIGURATION");
		ERROR_NAMES.put(ERROR_INDEX_ABSENT, "ERROR_INDEX_ABSENT");
		ERROR_NAMES.put(ERROR_INSTALL_SOURCE_ABSENT, "ERROR_INSTALL_SOURCE_ABSENT");
		ERROR_NAMES.put(ERROR_INSTALL_PACKAGE_VERSION, "ERROR_INSTALL_PACKAGE_VERSION");
		ERROR_NAMES.put(ERROR_PRODUCT_UNINSTALLED, "ERROR_PRODUCT_UNINSTALLED");
		ERROR_NAMES.put(ERROR_BAD_QUERY_SYNTAX, "ERROR_BAD_QUERY_SYNTAX");
		ERROR_NAMES.put(ERROR_INVALID_FIELD, "ERROR_INVALID_FIELD");
		ERROR_NAMES.put(ERROR_DEVICE_REMOVED, "ERROR_DEVICE_REMOVED");
		ERROR_NAMES.put(ERROR_INSTALL_ALREADY_RUNNING, "ERROR_INSTALL_ALREADY_RUNNING");
		ERROR_NAMES.put(ERROR_INSTALL_PACKAGE_OPEN_FAILED, "ERROR_INSTALL_PACKAGE_OPEN_FAILED");
		ERROR_NAMES.put(ERROR_INSTALL_PACKAGE_INVALID, "ERROR_INSTALL_PACKAGE_INVALID");
		ERROR_NAMES.put(ERROR_INSTALL_UI_FAILURE, "ERROR_INSTALL_UI_FAILURE");
		ERROR_NAMES.put(ERROR_INSTALL_LOG_FAILURE, "ERROR_INSTALL_LOG_FAILURE");
		ERROR_NAMES.put(ERROR_INSTALL_LANGUAGE_UNSUPPORTED, "ERROR_INSTALL_LANGUAGE_UNSUPPORTED");
		ERROR_NAMES.put(ERROR_INSTALL_TRANSFORM_FAILURE, "ERROR_INSTALL_TRANSFORM_FAILURE");
		ERROR_NAMES.put(ERROR_INSTALL_PACKAGE_REJECTED, "ERROR_INSTALL_PACKAGE_REJECTED");
		ERROR_NAMES.put(ERROR_FUNCTION_NOT_CALLED, "ERROR_FUNCTION_NOT_CALLED");
		ERROR_NAMES.put(ERROR_FUNCTION_FAILED, "ERROR_FUNCTION_FAILED");
		ERROR_NAMES.put(ERROR_INVALID_TABLE, "ERROR_INVALID_TABLE");
		ERROR_NAMES.put(ERROR_DATATYPE_MISMATCH, "ERROR_DATATYPE_MISMATCH");
		ERROR_NAMES.put(ERROR_UNSUPPORTED_TYPE, "ERROR_UNSUPPORTED_TYPE");
		ERROR_NAMES.put(ERROR_CREATE_FAILED, "ERROR_CREATE_FAILED");
		ERROR_NAMES.put(ERROR_INSTALL_TEMP_UNWRITABLE, "ERROR_INSTALL_TEMP_UNWRITABLE");
		ERROR_NAMES.put(ERROR_INSTALL_PLATFORM_UNSUPPORTED, "ERROR_INSTALL_PLATFORM_UNSUPPORTED");
		ERROR_NAMES.put(ERROR_INSTALL_NOTUSED, "ERROR_INSTALL_NOTUSED");
		ERROR_NAMES.put(ERROR_PATCH_PACKAGE_OPEN_FAILED, "ERROR_PATCH_PACKAGE_OPEN_FAILED");
		ERROR_NAMES.put(ERROR_PATCH_PACKAGE_INVALID, "ERROR_PATCH_PACKAGE_INVALID");
		ERROR_NAMES.put(ERROR_PATCH_PACKAGE_UNSUPPORTED, "ERROR_PATCH_PACKAGE_UNSUPPORTED");
		ERROR_NAMES.put(ERROR_PRODUCT_VERSION, "ERROR_PRODUCT_VERSION");
		ERROR_NAMES.put(ERROR_INVALID_COMMAND_LINE, "ERROR_INVALID_COMMAND_LINE");
		ERROR_NAMES.put(ERROR_INSTALL_REMOTE_DISALLOWED, "ERROR_INSTALL_REMOTE_DISALLOWED");
		ERROR_NAMES.put(ERROR_SUCCESS_REBOOT_INITIATED, "ERROR_SUCCESS_REBOOT_INITIATED");
		ERROR_NAMES.put(ERROR_PATCH_TARGET_NOT_FOUND, "ERROR_PATCH_TARGET_NOT_FOUND");
		ERROR_NAMES.put(ERROR_PATCH_PACKAGE_REJECTED, "ERROR_PATCH_PACKAGE_REJECTED");
		ERROR_NAMES.put(ERROR_INSTALL_TRANSFORM_REJECTED, "ERROR_INSTALL_TRANSFORM_REJECTED");
		ERROR_NAMES.put(ERROR_INSTALL_REMOTE_PROHIBITED, "ERROR_INSTALL_REMOTE_PROHIBITED");
	}

	public WinError(int errorcode) {
		super(getName(errorcode));
		this.errorcode = errorcode;
	}

	private static final String getName(int errorcode) {
		String name = ERROR_NAMES.get(errorcode);
		if(name != null) {
			return name;
		} else {
			return String.format("Error 0x%08X", errorcode);
		}
	}

	public int getError() {
		return errorcode;
	}
}
